In [1]:
import requests
import re
import json
import pandas as pd
import time
from urllib.parse import urlparse
from bs4 import BeautifulSoup
from dotenv import load_dotenv
import os

In [2]:
# 1. Obtener el HTML de la página del ranking
load_dotenv()
url = os.getenv("TARGET_URL_CPI")
BASE_URL = os.getenv("BASE_URL")

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Safari/537.36"
}

response = requests.get(url, headers=headers)
response.raise_for_status()  # Lanza error si la petición falla

In [3]:
# 2. Parsear HTML con BeautifulSoup
soup = BeautifulSoup(response.text, "html.parser")

In [4]:
# 3. Buscar la tabla principal y extraer los links
table = soup.find("table")
country_links = []


if table:
    rows = table.find_all("tr")
    for row in rows:
        cell = row.find("td")
        if cell and cell.a:
            relative_link = cell.a["href"]
            full_url = f"{BASE_URL}{relative_link}"
            country_links.append(full_url)

# Convertir la lista en DataFrame
df_links = pd.DataFrame(country_links, columns=["url"])

# Guardar como archivo Parquet
df_links.to_parquet("../../data/country_cpi_links.parquet", index=False)

In [5]:
# 4. Mostrar resultado
print("Links encontrados:", df_links.size)

Links encontrados: 182

In [6]:
# configuracion necesaria para descargar datos

master_df = pd.DataFrame()

pattern = r'arrayToDataTable\(\s*(\[\[.*?\]\])\s*\);'

sleep_duration = 5

In [7]:
master_df.head()

Empty DataFrame
Columns: []
Index: []

In [8]:
# Cargar los países válidos desde el archivo parquet
df_countries = pd.read_parquet("../../data/countries_with_hpi.parquet")
valid_countries = set(df_countries["country"].unique())

In [9]:
# DataFrames de salida
dfs_quarters = []
dfs_months = []

start_time = time.time()
for url in country_links:
    country = urlparse(url).path.strip("/").split("/")[0]

    if country not in valid_countries:
        print(f"⏭️ País {country} no está en la lista, se omite.")
        continue

    try:
        response = requests.get(url, headers=headers)
        html = response.text

        match = re.search(pattern, html, re.DOTALL)
        if match:
            data_str = match.group(1)
            data = json.loads(data_str)

            df = pd.DataFrame(data[1:], columns=data[0])
            df.columns = ["Period", "Value"]
            df["Country"] = country

            # --- separar según formato de Period ---
            if df["Period"].str.contains(r"Q\d").any():
                df_pivot = df.pivot(index="Period", columns="Country", values="Value")
                dfs_quarters.append(df_pivot)
                print(f"✅ Datos trimestrales extraídos para {country}")
            else:
                df_pivot = df.pivot(index="Period", columns="Country", values="Value")
                dfs_months.append(df_pivot)
                print(f"✅ Datos mensuales extraídos para {country}")
        else:
            print(f"⚠️ No se encontraron datos en {url}")
    except Exception as e:
        print(f"❌ Error procesando {url}: {e}")
    
    time.sleep(sleep_duration)

# unir cada grupo por separado
df_quarters = pd.concat(dfs_quarters, axis=1) if dfs_quarters else pd.DataFrame()
df_months = pd.concat(dfs_months, axis=1) if dfs_months else pd.DataFrame()

end_time = time.time()
total_sleep_time = len(valid_countries) * sleep_duration
effective_time = end_time - start_time - total_sleep_time

print(f"⏳ Tiempo total (incluyendo esperas): {end_time - start_time:.2f} s")
print(f"😴 Tiempo en espera: {total_sleep_time:.2f} s")
print(f"⚡ Tiempo efectivo de ejecución: {effective_time:.2f} s")

⏭️ País Afghanistan no está en la lista, se omite.
⏭️ País Albania no está en la lista, se omite.
⏭️ País Algeria no está en la lista, se omite.
⏭️ País Andorra no está en la lista, se omite.
⏭️ País Angola no está en la lista, se omite.
⏭️ País Antigua-and-Barbuda no está en la lista, se omite.
⏭️ País Argentina no está en la lista, se omite.
⏭️ País Armenia no está en la lista, se omite.
⏭️ País Aruba no está en la lista, se omite.
✅ Datos trimestrales extraídos para Australia
✅ Datos mensuales extraídos para Austria
⏭️ País Azerbaijan no está en la lista, se omite.
⏭️ País Bahamas no está en la lista, se omite.
⏭️ País Bahrain no está en la lista, se omite.
⏭️ País Bangladesh no está en la lista, se omite.
⏭️ País Barbados no está en la lista, se omite.
⏭️ País Belarus no está en la lista, se omite.
✅ Datos mensuales extraídos para Belgium
⏭️ País Belize no está en la lista, se omite.
⏭️ País Benin no está en la lista, se omite.
⏭️ País Bermuda no está en la lista, se omite.
⏭️ País Bhutan no está en la lista, se omite.
⏭️ País Bolivia no está en la lista, se omite.
⏭️ País Bosnia-and-Herzegovina no está en la lista, se omite.
⏭️ País Botswana no está en la lista, se omite.
✅ Datos mensuales extraídos para Brazil
⏭️ País Brunei no está en la lista, se omite.
✅ Datos mensuales extraídos para Bulgaria
⏭️ País Burkina-Faso no está en la lista, se omite.
⏭️ País Burma-Myanmar no está en la lista, se omite.
⏭️ País Burundi no está en la lista, se omite.
⏭️ País Cambodia no está en la lista, se omite.
⏭️ País Cameroon no está en la lista, se omite.
✅ Datos mensuales extraídos para Canada
⏭️ País Cape-Verde no está en la lista, se omite.
⏭️ País Chad no está en la lista, se omite.
✅ Datos mensuales extraídos para Chile
✅ Datos mensuales extraídos para China
✅ Datos mensuales extraídos para Colombia
⏭️ País Comoros no está en la lista, se omite.
⏭️ País Costa-Rica no está en la lista, se omite.
✅ Datos mensuales extraídos para Croatia
✅ Datos mensuales extraídos para Cyprus
✅ Datos mensuales extraídos para Czech-Republic
✅ Datos mensuales extraídos para Denmark
⏭️ País Djibouti no está en la lista, se omite.
⏭️ País Dominica no está en la lista, se omite.
⏭️ País Dominican-Republic no está en la lista, se omite.
⏭️ País Ecuador no está en la lista, se omite.
⏭️ País Egypt no está en la lista, se omite.
⏭️ País El-Salvador no está en la lista, se omite.
✅ Datos mensuales extraídos para Estonia
⏭️ País Ethiopia no está en la lista, se omite.
⏭️ País Euro_area no está en la lista, se omite.
⏭️ País Faroe-Islands no está en la lista, se omite.
⏭️ País Fiji no está en la lista, se omite.
✅ Datos mensuales extraídos para Finland
✅ Datos mensuales extraídos para France
⏭️ País Gambia no está en la lista, se omite.
⏭️ País Georgia no está en la lista, se omite.
✅ Datos mensuales extraídos para Germany
⏭️ País Ghana no está en la lista, se omite.
✅ Datos mensuales extraídos para Greece
⏭️ País Grenada no está en la lista, se omite.
⏭️ País Guatemala no está en la lista, se omite.
⏭️ País Guinea no está en la lista, se omite.
⏭️ País Guinea-Bissau no está en la lista, se omite.
⏭️ País Guyana no está en la lista, se omite.
⏭️ País Haiti no está en la lista, se omite.
⏭️ País Honduras no está en la lista, se omite.
✅ Datos mensuales extraídos para Hong-Kong
✅ Datos mensuales extraídos para Hungary
✅ Datos mensuales extraídos para Iceland
✅ Datos mensuales extraídos para India
✅ Datos mensuales extraídos para Indonesia
⏭️ País Iran no está en la lista, se omite.
⏭️ País Iraq no está en la lista, se omite.
✅ Datos mensuales extraídos para Ireland
✅ Datos mensuales extraídos para Israel
✅ Datos mensuales extraídos para Italy
⏭️ País Ivory-Coast no está en la lista, se omite.
⏭️ País Jamaica no está en la lista, se omite.
✅ Datos mensuales extraídos para Japan
⏭️ País Jordan no está en la lista, se omite.
⏭️ País Kazakhstan no está en la lista, se omite.
⏭️ País Kenya no está en la lista, se omite.
⏭️ País Kuwait no está en la lista, se omite.
⏭️ País Kyrgyzstan no está en la lista, se omite.
⏭️ País Laos no está en la lista, se omite.
✅ Datos mensuales extraídos para Latvia
⏭️ País Lebanon no está en la lista, se omite.
⏭️ País Lesotho no está en la lista, se omite.
⏭️ País Liberia no está en la lista, se omite.
⏭️ País Libya no está en la lista, se omite.
⏭️ País Liechtenstein no está en la lista, se omite.
✅ Datos mensuales extraídos para Lithuania
✅ Datos mensuales extraídos para Luxembourg
⏭️ País Macao no está en la lista, se omite.
✅ Datos mensuales extraídos para Macedonia
⏭️ País Madagascar no está en la lista, se omite.
⏭️ País Malawi no está en la lista, se omite.
✅ Datos mensuales extraídos para Malaysia
⏭️ País Maldives no está en la lista, se omite.
⏭️ País Mali no está en la lista, se omite.
✅ Datos mensuales extraídos para Malta
⏭️ País Mauritania no está en la lista, se omite.
⏭️ País Mauritius no está en la lista, se omite.
✅ Datos mensuales extraídos para Mexico
⏭️ País Moldova no está en la lista, se omite.
⏭️ País Mongolia no está en la lista, se omite.
⏭️ País Montenegro no está en la lista, se omite.
⏭️ País Montserrat no está en la lista, se omite.
✅ Datos mensuales extraídos para Morocco
⏭️ País Mozambique no está en la lista, se omite.
⏭️ País Namibia no está en la lista, se omite.
⏭️ País Nepal no está en la lista, se omite.
✅ Datos mensuales extraídos para Netherlands
⏭️ País New-Caledonia no está en la lista, se omite.
✅ Datos trimestrales extraídos para New-Zealand
⏭️ País Nicaragua no está en la lista, se omite.
⏭️ País Niger no está en la lista, se omite.
⏭️ País Nigeria no está en la lista, se omite.
✅ Datos mensuales extraídos para Norway
⏭️ País Oman no está en la lista, se omite.
⏭️ País Pakistan no está en la lista, se omite.
⏭️ País Palestine no está en la lista, se omite.
⏭️ País Panama no está en la lista, se omite.
⏭️ País Papua-New-Guinea no está en la lista, se omite.
⏭️ País Paraguay no está en la lista, se omite.
✅ Datos mensuales extraídos para Peru
✅ Datos mensuales extraídos para Philippines
✅ Datos mensuales extraídos para Poland
✅ Datos mensuales extraídos para Portugal
⏭️ País Puerto-Rico no está en la lista, se omite.
⏭️ País Qatar no está en la lista, se omite.
⏭️ País Republic-of-the-Congo no está en la lista, se omite.
✅ Datos mensuales extraídos para Romania
✅ Datos mensuales extraídos para Russia
⏭️ País Rwanda no está en la lista, se omite.
⏭️ País Saint-Lucia no está en la lista, se omite.
⏭️ País Saint-Vincent-and-the-Grenadines no está en la lista, se omite.
⏭️ País Samoa no está en la lista, se omite.
⏭️ País Sao-Tome-and-Principe no está en la lista, se omite.
⏭️ País Saudi-Arabia no está en la lista, se omite.
⏭️ País Senegal no está en la lista, se omite.
✅ Datos mensuales extraídos para Serbia
⏭️ País Seychelles no está en la lista, se omite.
⏭️ País Sierra-Leone no está en la lista, se omite.
✅ Datos mensuales extraídos para Singapore
✅ Datos mensuales extraídos para Slovakia
✅ Datos mensuales extraídos para Slovenia
⏭️ País Solomon-Islands no está en la lista, se omite.
⏭️ País Somalia no está en la lista, se omite.
✅ Datos mensuales extraídos para South-Africa
✅ Datos mensuales extraídos para South-Korea
✅ Datos mensuales extraídos para Spain
⏭️ País Sri-Lanka no está en la lista, se omite.
⏭️ País Sudan no está en la lista, se omite.
⏭️ País Suriname no está en la lista, se omite.
⏭️ País Swaziland no está en la lista, se omite.
✅ Datos mensuales extraídos para Sweden
✅ Datos mensuales extraídos para Switzerland
⏭️ País Taiwan no está en la lista, se omite.
⏭️ País Tajikistan no está en la lista, se omite.
⏭️ País Tanzania no está en la lista, se omite.
✅ Datos mensuales extraídos para Thailand
⏭️ País Togo no está en la lista, se omite.
⏭️ País Tonga no está en la lista, se omite.
⏭️ País Trinidad-and-Tobago no está en la lista, se omite.
⏭️ País Tunisia no está en la lista, se omite.
✅ Datos mensuales extraídos para Turkey
✅ Datos mensuales extraídos para USA
⏭️ País Uganda no está en la lista, se omite.
⏭️ País Ukraine no está en la lista, se omite.
⏭️ País United-Arab-Emirates no está en la lista, se omite.
✅ Datos mensuales extraídos para United-Kingdom
⏭️ País Uruguay no está en la lista, se omite.
⏭️ País Vanuatu no está en la lista, se omite.
⏭️ País Venezuela no está en la lista, se omite.
⏭️ País Vietnam no está en la lista, se omite.
⏭️ País Zambia no está en la lista, se omite.
⏭️ País Zimbabwe no está en la lista, se omite.
⏳ Tiempo total (incluyendo esperas): 369.32 s
😴 Tiempo en espera: 285.00 s
⚡ Tiempo efectivo de ejecución: 84.32 s

In [10]:
# resultados finales
print("\n📊 DataFrame trimestral")
df_quarters.head()

📊 DataFrame trimestral

Country  Australia  New-Zealand
Period
Q1 1960        7.5      44.8764
Q1 1961        7.8      45.5819
Q1 1962        7.8      46.9145
Q1 1963        7.8      47.7767
Q1 1964        8.0      48.9917

In [30]:
print("\n📊 DataFrame mensual")
df_months.head()

📊 DataFrame mensual

Country,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,Colombia,Croatia,Cyprus,...,Slovenia,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom
Period,,,,,,,,,,,,,,,,,,,,,
Apr 1996,71.69,70.47,1298.65,NaN,88.5,60.405,80.6937,24.21,NaN,66.76,...,45.76,NaN,54.226,64.73,76.49,NaN,60.2458,1.42,156.1,68.7
Apr 1997,72.56,71.25,1405.18,39.84,90.2,64.062,83.2759,28.69,NaN,69.43,...,48.92,NaN,56.565,65.77,77.39,NaN,62.7807,2.50,159.9,69.8
Apr 1998,73.42,72.16,1459.71,49.05,91.1,67.511,83.0260,34.65,63.74,70.47,...,53.37,NaN,61.557,67.01,78.49,NaN,69.0334,4.80,162.2,71.1
Apr 1999,73.49,72.94,1508.55,47.95,92.0,70.234,81.1995,38.51,65.96,70.83,...,55.80,NaN,61.816,68.56,78.74,NaN,69.3714,7.76,165.9,72.2
Apr 2000,74.78,74.63,1610.75,52.36,94.8,72.715,80.9559,42.35,68.53,74.98,...,60.98,NaN,62.709,70.64,79.49,NaN,69.7000,12.52,170.9,72.6

---

In [12]:
# obtain paraguay url
template_url = country_links[0]
country = "Paraguay"

# Separar por "/"
parts = template_url.strip("/").split("/")

# Reemplazar el país (posición 3: después del dominio)

parts[3] = country

# Reconstruir la URL
custom_url = "/".join(parts) + "/"

In [13]:
# URL específica para Paraguay
response = requests.get(custom_url, headers=headers)
html = response.text

# Buscar el bloque JSON dentro del HTML
match = re.search(pattern, html, re.DOTALL)
if match:
    data_str = match.group(1)
    data = json.loads(data_str)

    # Crear DataFrame con los datos
    df = pd.DataFrame(data[1:], columns=data[0])
    df.columns = ["Period", "Value"]
    df["Country"] = "Paraguay"  # Asignar explícitamente

    # Pivotear para formato ancho (opcional)
    df_paraguay = df.pivot(index="Period", columns="Country", values="Value")

    print("✅ Datos de Paraguay extraídos correctamente")
else:
    print("⚠️ No se encontraron datos en el HTML para Paraguay")

✅ Datos de Paraguay extraídos correctamente

In [32]:
df_paraguay.head()

Country   Paraguay
Period
Apr 1995   22.2615
Apr 1996   24.6815
Apr 1997   26.6891
Apr 1998   28.9441
Apr 1999   31.1579

In [15]:
# Unir ambos DataFrames por el índice 'Period', preservando todos los datos
new_month_df = pd.merge(df_months, df_paraguay, how="outer", left_index=True, right_index=True)

In [31]:
new_month_df.head()

Country,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,Colombia,Croatia,Cyprus,...,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay
Period,,,,,,,,,,,,,,,,,,,,,
Apr 1960,NaN,NaN,NaN,NaN,15.5,NaN,NaN,0.0401,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.54,NaN,NaN
Apr 1961,NaN,NaN,NaN,NaN,15.7,NaN,NaN,0.0440,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,29.81,NaN,NaN
Apr 1962,NaN,NaN,NaN,NaN,15.7,NaN,NaN,0.0456,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.21,NaN,NaN
Apr 1963,NaN,NaN,NaN,NaN,16.0,NaN,NaN,0.0571,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.48,NaN,NaN
Apr 1964,NaN,NaN,NaN,NaN,16.3,NaN,NaN,0.0674,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.95,NaN,NaN

In [25]:
unique_periods = pd.Series(new_month_df.index.astype(str)).unique()
print(unique_periods)

['Apr 1960' 'Apr 1961' 'Apr 1962' 'Apr 1963' 'Apr 1964' 'Apr 1965'
 'Apr 1966' 'Apr 1967' 'Apr 1968' 'Apr 1969' 'Apr 1970' 'Apr 1971'
 'Apr 1972' 'Apr 1973' 'Apr 1974' 'Apr 1975' 'Apr 1976' 'Apr 1977'
 'Apr 1978' 'Apr 1979' 'Apr 1980' 'Apr 1981' 'Apr 1982' 'Apr 1983'
 'Apr 1984' 'Apr 1985' 'Apr 1986' 'Apr 1987' 'Apr 1988' 'Apr 1989'
 'Apr 1990' 'Apr 1991' 'Apr 1992' 'Apr 1993' 'Apr 1994' 'Apr 1995'
 'Apr 1996' 'Apr 1997' 'Apr 1998' 'Apr 1999' 'Apr 2000' 'Apr 2001'
 'Apr 2002' 'Apr 2003' 'Apr 2004' 'Apr 2005' 'Apr 2006' 'Apr 2007'
 'Apr 2008' 'Apr 2009' 'Apr 2010' 'Apr 2011' 'Apr 2012' 'Apr 2013'
 'Apr 2014' 'Apr 2015' 'Apr 2016' 'Apr 2017' 'Apr 2018' 'Apr 2019'
 'Apr 2020' 'Apr 2021' 'Apr 2022' 'Apr 2023' 'Apr 2024' 'Apr 2025'
 'Aug 1960' 'Aug 1961' 'Aug 1962' 'Aug 1963' 'Aug 1964' 'Aug 1965'
 'Aug 1966' 'Aug 1967' 'Aug 1968' 'Aug 1969' 'Aug 1970' 'Aug 1971'
 'Aug 1972' 'Aug 1973' 'Aug 1974' 'Aug 1975' 'Aug 1976' 'Aug 1977'
 'Aug 1978' 'Aug 1979' 'Aug 1980' 'Aug 1981' 'Aug 1982' 'Aug 1983'
 'Aug 1984' 'Aug 1985' 'Aug 1986' 'Aug 1987' 'Aug 1988' 'Aug 1989'
 'Aug 1990' 'Aug 1991' 'Aug 1992' 'Aug 1993' 'Aug 1994' 'Aug 1995'
 'Aug 1996' 'Aug 1997' 'Aug 1998' 'Aug 1999' 'Aug 2000' 'Aug 2001'
 'Aug 2002' 'Aug 2003' 'Aug 2004' 'Aug 2005' 'Aug 2006' 'Aug 2007'
 'Aug 2008' 'Aug 2009' 'Aug 2010' 'Aug 2011' 'Aug 2012' 'Aug 2013'
 'Aug 2014' 'Aug 2015' 'Aug 2016' 'Aug 2017' 'Aug 2018' 'Aug 2019'
 'Aug 2020' 'Aug 2021' 'Aug 2022' 'Aug 2023' 'Aug 2024' 'Dec 1960'
 'Dec 1961' 'Dec 1962' 'Dec 1963' 'Dec 1964' 'Dec 1965' 'Dec 1966'
 'Dec 1967' 'Dec 1968' 'Dec 1969' 'Dec 1970' 'Dec 1971' 'Dec 1972'
 'Dec 1973' 'Dec 1974' 'Dec 1975' 'Dec 1976' 'Dec 1977' 'Dec 1978'
 'Dec 1979' 'Dec 1980' 'Dec 1981' 'Dec 1982' 'Dec 1983' 'Dec 1984'
 'Dec 1985' 'Dec 1986' 'Dec 1987' 'Dec 1988' 'Dec 1989' 'Dec 1990'
 'Dec 1991' 'Dec 1992' 'Dec 1993' 'Dec 1994' 'Dec 1995' 'Dec 1996'
 'Dec 1997' 'Dec 1998' 'Dec 1999' 'Dec 2000' 'Dec 2001' 'Dec 2002'
 'Dec 2003' 'Dec 2004' 'Dec 2005' 'Dec 2006' 'Dec 2007' 'Dec 2008'
 'Dec 2009' 'Dec 2010' 'Dec 2011' 'Dec 2012' 'Dec 2013' 'Dec 2014'
 'Dec 2015' 'Dec 2016' 'Dec 2017' 'Dec 2018' 'Dec 2019' 'Dec 2020'
 'Dec 2021' 'Dec 2022' 'Dec 2023' 'Dec 2024' 'Feb 1960' 'Feb 1961'
 'Feb 1962' 'Feb 1963' 'Feb 1964' 'Feb 1965' 'Feb 1966' 'Feb 1967'
 'Feb 1968' 'Feb 1969' 'Feb 1970' 'Feb 1971' 'Feb 1972' 'Feb 1973'
 'Feb 1974' 'Feb 1975' 'Feb 1976' 'Feb 1977' 'Feb 1978' 'Feb 1979'
 'Feb 1980' 'Feb 1981' 'Feb 1982' 'Feb 1983' 'Feb 1984' 'Feb 1985'
 'Feb 1986' 'Feb 1987' 'Feb 1988' 'Feb 1989' 'Feb 1990' 'Feb 1991'
 'Feb 1992' 'Feb 1993' 'Feb 1994' 'Feb 1995' 'Feb 1996' 'Feb 1997'
 'Feb 1998' 'Feb 1999' 'Feb 2000' 'Feb 2001' 'Feb 2002' 'Feb 2003'
 'Feb 2004' 'Feb 2005' 'Feb 2006' 'Feb 2007' 'Feb 2008' 'Feb 2009'
 'Feb 2010' 'Feb 2011' 'Feb 2012' 'Feb 2013' 'Feb 2014' 'Feb 2015'
 'Feb 2016' 'Feb 2017' 'Feb 2018' 'Feb 2019' 'Feb 2020' 'Feb 2021'
 'Feb 2022' 'Feb 2023' 'Feb 2024' 'Feb 2025' 'Jan 1960' 'Jan 1961'
 'Jan 1962' 'Jan 1963' 'Jan 1964' 'Jan 1965' 'Jan 1966' 'Jan 1967'
 'Jan 1968' 'Jan 1969' 'Jan 1970' 'Jan 1971' 'Jan 1972' 'Jan 1973'
 'Jan 1974' 'Jan 1975' 'Jan 1976' 'Jan 1977' 'Jan 1978' 'Jan 1979'
 'Jan 1980' 'Jan 1981' 'Jan 1982' 'Jan 1983' 'Jan 1984' 'Jan 1985'
 'Jan 1986' 'Jan 1987' 'Jan 1988' 'Jan 1989' 'Jan 1990' 'Jan 1991'
 'Jan 1992' 'Jan 1993' 'Jan 1994' 'Jan 1995' 'Jan 1996' 'Jan 1997'
 'Jan 1998' 'Jan 1999' 'Jan 2000' 'Jan 2001' 'Jan 2002' 'Jan 2003'
 'Jan 2004' 'Jan 2005' 'Jan 2006' 'Jan 2007' 'Jan 2008' 'Jan 2009'
 'Jan 2010' 'Jan 2011' 'Jan 2012' 'Jan 2013' 'Jan 2014' 'Jan 2015'
 'Jan 2016' 'Jan 2017' 'Jan 2018' 'Jan 2019' 'Jan 2020' 'Jan 2021'
 'Jan 2022' 'Jan 2023' 'Jan 2024' 'Jan 2025' 'Jul 1960' 'Jul 1961'
 'Jul 1962' 'Jul 1963' 'Jul 1964' 'Jul 1965' 'Jul 1966' 'Jul 1967'
 'Jul 1968' 'Jul 1969' 'Jul 1970' 'Jul 1971' 'Jul 1972' 'Jul 1973'
 'Jul 1974' 'Jul 1975' 'Jul 1976' 'Jul 1977' 'Jul 1978' 'Jul 1979'
 'Jul 1980' 'Jul 1981' 'Jul 1982' 'Jul 1983' 'Jul 1984' 'Jul 1985'
 'Jul 1986' 'Jul 1987' 'Jul 1988' 'Jul 1989' 'Jul 1990' 'Jul 1991'
 'Jul 1992' 'Jul 1993' 'Jul 1994' 'Jul 1995' 'Jul 1996' 'Jul 1997'
 'Jul 1998' 'Jul 1999' 'Jul 2000' 'Jul 2001' 'Jul 2002' 'Jul 2003'
 'Jul 2004' 'Jul 2005' 'Jul 2006' 'Jul 2007' 'Jul 2008' 'Jul 2009'
 'Jul 2010' 'Jul 2011' 'Jul 2012' 'Jul 2013' 'Jul 2014' 'Jul 2015'
 'Jul 2016' 'Jul 2017' 'Jul 2018' 'Jul 2019' 'Jul 2020' 'Jul 2021'
 'Jul 2022' 'Jul 2023' 'Jul 2024' 'Jul 2025' 'June 1960' 'June 1961'
 'June 1962' 'June 1963' 'June 1964' 'June 1965' 'June 1966' 'June 1967'
 'June 1968' 'June 1969' 'June 1970' 'June 1971' 'June 1972' 'June 1973'
 'June 1974' 'June 1975' 'June 1976' 'June 1977' 'June 1978' 'June 1979'
 'June 1980' 'June 1981' 'June 1982' 'June 1983' 'June 1984' 'June 1985'
 'June 1986' 'June 1987' 'June 1988' 'June 1989' 'June 1990' 'June 1991'
 'June 1992' 'June 1993' 'June 1994' 'June 1995' 'June 1996' 'June 1997'
 'June 1998' 'June 1999' 'June 2000' 'June 2001' 'June 2002' 'June 2003'
 'June 2004' 'June 2005' 'June 2006' 'June 2007' 'June 2008' 'June 2009'
 'June 2010' 'June 2011' 'June 2012' 'June 2013' 'June 2014' 'June 2015'
 'June 2016' 'June 2017' 'June 2018' 'June 2019' 'June 2020' 'June 2021'
 'June 2022' 'June 2023' 'June 2024' 'June 2025' 'Mar 1960' 'Mar 1961'
 'Mar 1962' 'Mar 1963' 'Mar 1964' 'Mar 1965' 'Mar 1966' 'Mar 1967'
 'Mar 1968' 'Mar 1969' 'Mar 1970' 'Mar 1971' 'Mar 1972' 'Mar 1973'
 'Mar 1974' 'Mar 1975' 'Mar 1976' 'Mar 1977' 'Mar 1978' 'Mar 1979'
 'Mar 1980' 'Mar 1981' 'Mar 1982' 'Mar 1983' 'Mar 1984' 'Mar 1985'
 'Mar 1986' 'Mar 1987' 'Mar 1988' 'Mar 1989' 'Mar 1990' 'Mar 1991'
 'Mar 1992' 'Mar 1993' 'Mar 1994' 'Mar 1995' 'Mar 1996' 'Mar 1997'
 'Mar 1998' 'Mar 1999' 'Mar 2000' 'Mar 2001' 'Mar 2002' 'Mar 2003'
 'Mar 2004' 'Mar 2005' 'Mar 2006' 'Mar 2007' 'Mar 2008' 'Mar 2009'
 'Mar 2010' 'Mar 2011' 'Mar 2012' 'Mar 2013' 'Mar 2014' 'Mar 2015'
 'Mar 2016' 'Mar 2017' 'Mar 2018' 'Mar 2019' 'Mar 2020' 'Mar 2021'
 'Mar 2022' 'Mar 2023' 'Mar 2024' 'Mar 2025' 'May 1960' 'May 1961'
 'May 1962' 'May 1963' 'May 1964' 'May 1965' 'May 1966' 'May 1967'
 'May 1968' 'May 1969' 'May 1970' 'May 1971' 'May 1972' 'May 1973'
 'May 1974' 'May 1975' 'May 1976' 'May 1977' 'May 1978' 'May 1979'
 'May 1980' 'May 1981' 'May 1982' 'May 1983' 'May 1984' 'May 1985'
 'May 1986' 'May 1987' 'May 1988' 'May 1989' 'May 1990' 'May 1991'
 'May 1992' 'May 1993' 'May 1994' 'May 1995' 'May 1996' 'May 1997'
 'May 1998' 'May 1999' 'May 2000' 'May 2001' 'May 2002' 'May 2003'
 'May 2004' 'May 2005' 'May 2006' 'May 2007' 'May 2008' 'May 2009'
 'May 2010' 'May 2011' 'May 2012' 'May 2013' 'May 2014' 'May 2015'
 'May 2016' 'May 2017' 'May 2018' 'May 2019' 'May 2020' 'May 2021'
 'May 2022' 'May 2023' 'May 2024' 'May 2025' 'Nov 1960' 'Nov 1961'
 'Nov 1962' 'Nov 1963' 'Nov 1964' 'Nov 1965' 'Nov 1966' 'Nov 1967'
 'Nov 1968' 'Nov 1969' 'Nov 1970' 'Nov 1971' 'Nov 1972' 'Nov 1973'
 'Nov 1974' 'Nov 1975' 'Nov 1976' 'Nov 1977' 'Nov 1978' 'Nov 1979'
 'Nov 1980' 'Nov 1981' 'Nov 1982' 'Nov 1983' 'Nov 1984' 'Nov 1985'
 'Nov 1986' 'Nov 1987' 'Nov 1988' 'Nov 1989' 'Nov 1990' 'Nov 1991'
 'Nov 1992' 'Nov 1993' 'Nov 1994' 'Nov 1995' 'Nov 1996' 'Nov 1997'
 'Nov 1998' 'Nov 1999' 'Nov 2000' 'Nov 2001' 'Nov 2002' 'Nov 2003'
 'Nov 2004' 'Nov 2005' 'Nov 2006' 'Nov 2007' 'Nov 2008' 'Nov 2009'
 'Nov 2010' 'Nov 2011' 'Nov 2012' 'Nov 2013' 'Nov 2014' 'Nov 2015'
 'Nov 2016' 'Nov 2017' 'Nov 2018' 'Nov 2019' 'Nov 2020' 'Nov 2021'
 'Nov 2022' 'Nov 2023' 'Nov 2024' 'Oct 1960' 'Oct 1961' 'Oct 1962'
 'Oct 1963' 'Oct 1964' 'Oct 1965' 'Oct 1966' 'Oct 1967' 'Oct 1968'
 'Oct 1969' 'Oct 1970' 'Oct 1971' 'Oct 1972' 'Oct 1973' 'Oct 1974'
 'Oct 1975' 'Oct 1976' 'Oct 1977' 'Oct 1978' 'Oct 1979' 'Oct 1980'
 'Oct 1981' 'Oct 1982' 'Oct 1983' 'Oct 1984' 'Oct 1985' 'Oct 1986'
 'Oct 1987' 'Oct 1988' 'Oct 1989' 'Oct 1990' 'Oct 1991' 'Oct 1992'
 'Oct 1993' 'Oct 1994' 'Oct 1995' 'Oct 1996' 'Oct 1997' 'Oct 1998'
 'Oct 1999' 'Oct 2000' 'Oct 2001' 'Oct 2002' 'Oct 2003' 'Oct 2004'
 'Oct 2005' 'Oct 2006' 'Oct 2007' 'Oct 2008' 'Oct 2009' 'Oct 2010'
 'Oct 2011' 'Oct 2012' 'Oct 2013' 'Oct 2014' 'Oct 2015' 'Oct 2016'
 'Oct 2017' 'Oct 2018' 'Oct 2019' 'Oct 2020' 'Oct 2021' 'Oct 2022'
 'Oct 2023' 'Oct 2024' 'Sep 1960' 'Sep 1961' 'Sep 1962' 'Sep 1963'
 'Sep 1964' 'Sep 1965' 'Sep 1966' 'Sep 1967' 'Sep 1968' 'Sep 1969'
 'Sep 1970' 'Sep 1971' 'Sep 1972' 'Sep 1973' 'Sep 1974' 'Sep 1975'
 'Sep 1976' 'Sep 1977' 'Sep 1978' 'Sep 1979' 'Sep 1980' 'Sep 1981'
 'Sep 1982' 'Sep 1983' 'Sep 1984' 'Sep 1985' 'Sep 1986' 'Sep 1987'
 'Sep 1988' 'Sep 1989' 'Sep 1990' 'Sep 1991' 'Sep 1992' 'Sep 1993'
 'Sep 1994' 'Sep 1995' 'Sep 1996' 'Sep 1997' 'Sep 1998' 'Sep 1999'
 'Sep 2000' 'Sep 2001' 'Sep 2002' 'Sep 2003' 'Sep 2004' 'Sep 2005'
 'Sep 2006' 'Sep 2007' 'Sep 2008' 'Sep 2009' 'Sep 2010' 'Sep 2011'
 'Sep 2012' 'Sep 2013' 'Sep 2014' 'Sep 2015' 'Sep 2016' 'Sep 2017'
 'Sep 2018' 'Sep 2019' 'Sep 2020' 'Sep 2021' 'Sep 2022' 'Sep 2023'
 'Sep 2024']

In [26]:
unique_periods = pd.Series(df_quarters.index.astype(str)).unique()
print(unique_periods)

['Q1 1960' 'Q1 1961' 'Q1 1962' 'Q1 1963' 'Q1 1964' 'Q1 1965' 'Q1 1966'
 'Q1 1967' 'Q1 1968' 'Q1 1969' 'Q1 1970' 'Q1 1971' 'Q1 1972' 'Q1 1973'
 'Q1 1974' 'Q1 1975' 'Q1 1976' 'Q1 1977' 'Q1 1978' 'Q1 1979' 'Q1 1980'
 'Q1 1981' 'Q1 1982' 'Q1 1983' 'Q1 1984' 'Q1 1985' 'Q1 1986' 'Q1 1987'
 'Q1 1988' 'Q1 1989' 'Q1 1990' 'Q1 1991' 'Q1 1992' 'Q1 1993' 'Q1 1994'
 'Q1 1995' 'Q1 1996' 'Q1 1997' 'Q1 1998' 'Q1 1999' 'Q1 2000' 'Q1 2001'
 'Q1 2002' 'Q1 2003' 'Q1 2004' 'Q1 2005' 'Q1 2006' 'Q1 2007' 'Q1 2008'
 'Q1 2009' 'Q1 2010' 'Q1 2011' 'Q1 2012' 'Q1 2013' 'Q1 2014' 'Q1 2015'
 'Q1 2016' 'Q1 2017' 'Q1 2018' 'Q1 2019' 'Q1 2020' 'Q1 2021' 'Q1 2022'
 'Q1 2023' 'Q1 2024' 'Q1 2025' 'Q2 1960' 'Q2 1961' 'Q2 1962' 'Q2 1963'
 'Q2 1964' 'Q2 1965' 'Q2 1966' 'Q2 1967' 'Q2 1968' 'Q2 1969' 'Q2 1970'
 'Q2 1971' 'Q2 1972' 'Q2 1973' 'Q2 1974' 'Q2 1975' 'Q2 1976' 'Q2 1977'
 'Q2 1978' 'Q2 1979' 'Q2 1980' 'Q2 1981' 'Q2 1982' 'Q2 1983' 'Q2 1984'
 'Q2 1985' 'Q2 1986' 'Q2 1987' 'Q2 1988' 'Q2 1989' 'Q2 1990' 'Q2 1991'
 'Q2 1992' 'Q2 1993' 'Q2 1994' 'Q2 1995' 'Q2 1996' 'Q2 1997' 'Q2 1998'
 'Q2 1999' 'Q2 2000' 'Q2 2001' 'Q2 2002' 'Q2 2003' 'Q2 2004' 'Q2 2005'
 'Q2 2006' 'Q2 2007' 'Q2 2008' 'Q2 2009' 'Q2 2010' 'Q2 2011' 'Q2 2012'
 'Q2 2013' 'Q2 2014' 'Q2 2015' 'Q2 2016' 'Q2 2017' 'Q2 2018' 'Q2 2019'
 'Q2 2020' 'Q2 2021' 'Q2 2022' 'Q2 2023' 'Q2 2024' 'Q2 2025' 'Q3 1960'
 'Q3 1961' 'Q3 1962' 'Q3 1963' 'Q3 1964' 'Q3 1965' 'Q3 1966' 'Q3 1967'
 'Q3 1968' 'Q3 1969' 'Q3 1970' 'Q3 1971' 'Q3 1972' 'Q3 1973' 'Q3 1974'
 'Q3 1975' 'Q3 1976' 'Q3 1977' 'Q3 1978' 'Q3 1979' 'Q3 1980' 'Q3 1981'
 'Q3 1982' 'Q3 1983' 'Q3 1984' 'Q3 1985' 'Q3 1986' 'Q3 1987' 'Q3 1988'
 'Q3 1989' 'Q3 1990' 'Q3 1991' 'Q3 1992' 'Q3 1993' 'Q3 1994' 'Q3 1995'
 'Q3 1996' 'Q3 1997' 'Q3 1998' 'Q3 1999' 'Q3 2000' 'Q3 2001' 'Q3 2002'
 'Q3 2003' 'Q3 2004' 'Q3 2005' 'Q3 2006' 'Q3 2007' 'Q3 2008' 'Q3 2009'
 'Q3 2010' 'Q3 2011' 'Q3 2012' 'Q3 2013' 'Q3 2014' 'Q3 2015' 'Q3 2016'
 'Q3 2017' 'Q3 2018' 'Q3 2019' 'Q3 2020' 'Q3 2021' 'Q3 2022' 'Q3 2023'
 'Q3 2024' 'Q4 1960' 'Q4 1961' 'Q4 1962' 'Q4 1963' 'Q4 1964' 'Q4 1965'
 'Q4 1966' 'Q4 1967' 'Q4 1968' 'Q4 1969' 'Q4 1970' 'Q4 1971' 'Q4 1972'
 'Q4 1973' 'Q4 1974' 'Q4 1975' 'Q4 1976' 'Q4 1977' 'Q4 1978' 'Q4 1979'
 'Q4 1980' 'Q4 1981' 'Q4 1982' 'Q4 1983' 'Q4 1984' 'Q4 1985' 'Q4 1986'
 'Q4 1987' 'Q4 1988' 'Q4 1989' 'Q4 1990' 'Q4 1991' 'Q4 1992' 'Q4 1993'
 'Q4 1994' 'Q4 1995' 'Q4 1996' 'Q4 1997' 'Q4 1998' 'Q4 1999' 'Q4 2000'
 'Q4 2001' 'Q4 2002' 'Q4 2003' 'Q4 2004' 'Q4 2005' 'Q4 2006' 'Q4 2007'
 'Q4 2008' 'Q4 2009' 'Q4 2010' 'Q4 2011' 'Q4 2012' 'Q4 2013' 'Q4 2014'
 'Q4 2015' 'Q4 2016' 'Q4 2017' 'Q4 2018' 'Q4 2019' 'Q4 2020' 'Q4 2021'
 'Q4 2022' 'Q4 2023' 'Q4 2024']

In [33]:
def split_period_index(df):
    """
    Recibe un DataFrame con índice 'Period' (ej: 'Apr 1960' o 'Q1 1990')
    Devuelve el mismo DataFrame con columnas 'Year' y 'Month' o 'Quarter'
    """
    df = df.copy().reset_index()  # sacar Period del índice
    df["Year"] = None
    df["Month"] = None
    df["Quarter"] = None

    for i, period in enumerate(df["Period"]):
        parts = period.split()

        if len(parts) == 2:
            first, year = parts
            df.at[i, "Year"] = int(year)

            if "Q" in first:  # Formato trimestral
                df.at[i, "Quarter"] = first
            else:  # Formato mensual
                df.at[i, "Month"] = first

    return df.set_index("Period")  # opcional: devolver con Period otra vez de índice

In [34]:
new_month_df = split_period_index(new_month_df)

In [35]:
new_month_df.head()

Country,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,Colombia,Croatia,Cyprus,...,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay,Year,Month,Quarter
Period,,,,,,,,,,,,,,,,,,,,,
Apr 1960,NaN,NaN,NaN,NaN,15.5,NaN,NaN,0.0401,NaN,NaN,...,NaN,NaN,NaN,NaN,29.54,NaN,NaN,1960,Apr,None
Apr 1961,NaN,NaN,NaN,NaN,15.7,NaN,NaN,0.0440,NaN,NaN,...,NaN,NaN,NaN,NaN,29.81,NaN,NaN,1961,Apr,None
Apr 1962,NaN,NaN,NaN,NaN,15.7,NaN,NaN,0.0456,NaN,NaN,...,NaN,NaN,NaN,NaN,30.21,NaN,NaN,1962,Apr,None
Apr 1963,NaN,NaN,NaN,NaN,16.0,NaN,NaN,0.0571,NaN,NaN,...,NaN,NaN,NaN,NaN,30.48,NaN,NaN,1963,Apr,None
Apr 1964,NaN,NaN,NaN,NaN,16.3,NaN,NaN,0.0674,NaN,NaN,...,NaN,NaN,NaN,NaN,30.95,NaN,NaN,1964,Apr,None

In [36]:
new_month_df.tail()

Country,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,Colombia,Croatia,Cyprus,...,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay,Year,Month,Quarter
Period,,,,,,,,,,,,,,,,,,,,,
Sep 2020,108.67,108.21,5391.75,105.70,136.9,79.72,127.9984,105.29,103.18,99.70,...,108.06,100.44,102.18,182.90,260.280,109.1,106.6,2020,Sep,None
Sep 2021,112.23,112.35,5944.21,109.92,142.9,83.98,128.4814,110.04,106.80,103.31,...,111.29,101.29,101.21,218.71,274.310,112.4,113.4,2021,Sep,None
Sep 2022,124.58,125.90,6370.34,127.10,152.7,95.51,131.9948,122.63,120.21,112.63,...,122.70,104.53,107.70,401.10,296.808,122.3,124.0,2022,Sep,None
Sep 2023,131.75,126.73,6700.66,135.18,158.5,100.39,132.1184,136.11,129.15,117.48,...,127.19,106.57,108.02,648.45,307.789,130.1,128.3,2023,Sep,None
Sep 2024,134.13,132.21,6997.15,137.25,161.1,104.54,132.7618,144.02,133.11,119.41,...,128.76,107.50,108.68,969.11,315.301,133.5,133.5,2024,Sep,None

In [37]:
new_quarter_df = split_period_index(df_quarters)
new_quarter_df.head()

Country  Australia  New-Zealand  Year Month Quarter
Period
Q1 1960        7.5      44.8764  1960  None      Q1
Q1 1961        7.8      45.5819  1961  None      Q1
Q1 1962        7.8      46.9145  1962  None      Q1
Q1 1963        7.8      47.7767  1963  None      Q1
Q1 1964        8.0      48.9917  1964  None      Q1

In [43]:
def month_to_quarter(df):
    """
    Takes a DataFrame with 'Month' and 'Quarter' columns.
    If 'Month' exists, it assigns the corresponding quarter to 'Quarter'.
    """
    df = df.copy()

    # Dictionary for mapping months → quarters
    month_to_q = {
        "Jan": 1, "Feb": 1, "Mar": 1,
        "Apr": 2, "May": 2, "June": 2,
        "Jul": 3, "Aug": 3, "Sep": 3,
        "Oct": 4, "Nov": 4, "Dec": 4,
    }

    # Update quarter only where Month exists
    df["Quarter"] = df.apply(
        lambda row: month_to_q.get(row["Month"], row["Quarter"]),
        axis=1
    )

    return df

In [44]:
new_month_df = month_to_quarter(new_month_df)

In [45]:
new_month_df.tail()

Country,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,Colombia,Croatia,Cyprus,...,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay,Year,Month,Quarter
Period,,,,,,,,,,,,,,,,,,,,,
Sep 2020,108.67,108.21,5391.75,105.70,136.9,79.72,127.9984,105.29,103.18,99.70,...,108.06,100.44,102.18,182.90,260.280,109.1,106.6,2020,Sep,3
Sep 2021,112.23,112.35,5944.21,109.92,142.9,83.98,128.4814,110.04,106.80,103.31,...,111.29,101.29,101.21,218.71,274.310,112.4,113.4,2021,Sep,3
Sep 2022,124.58,125.90,6370.34,127.10,152.7,95.51,131.9948,122.63,120.21,112.63,...,122.70,104.53,107.70,401.10,296.808,122.3,124.0,2022,Sep,3
Sep 2023,131.75,126.73,6700.66,135.18,158.5,100.39,132.1184,136.11,129.15,117.48,...,127.19,106.57,108.02,648.45,307.789,130.1,128.3,2023,Sep,3
Sep 2024,134.13,132.21,6997.15,137.25,161.1,104.54,132.7618,144.02,133.11,119.41,...,128.76,107.50,108.68,969.11,315.301,133.5,133.5,2024,Sep,3

In [46]:
def quarter_to_int(df):
    """
    Convierte los valores de la columna 'Quarter' a enteros (Q1 → 1, Q2 → 2, etc.)
    """
    df = df.copy()

    q_map = {"Q1": 1, "Q2": 2, "Q3": 3, "Q4": 4}

    df["Quarter"] = df["Quarter"].map(q_map).fillna(df["Quarter"])

    return df

In [47]:
new_quarter_df = quarter_to_int(new_quarter_df)
new_quarter_df.head()

Country  Australia  New-Zealand  Year Month  Quarter
Period
Q1 1960        7.5      44.8764  1960  None        1
Q1 1961        7.8      45.5819  1961  None        1
Q1 1962        7.8      46.9145  1962  None        1
Q1 1963        7.8      47.7767  1963  None        1
Q1 1964        8.0      48.9917  1964  None        1

In [48]:
new_quarter_df.dtypes

Country
Australia      float64
New-Zealand    float64
Year            object
Month           object
Quarter          int64
dtype: object

In [49]:
def year_to_int(df):
    """
    Convierte la columna 'Year' a enteros.
    Si hay valores no numéricos, los convierte en NaN.
    """
    df = df.copy()
    df["Year"] = pd.to_numeric(df["Year"], errors="coerce").astype("Int64")
    return df

In [50]:
new_quarter_df = year_to_int(new_quarter_df)
new_quarter_df.dtypes

Country
Australia      float64
New-Zealand    float64
Year             Int64
Month           object
Quarter          int64
dtype: object

In [51]:
new_quarter_df.head()

Country  Australia  New-Zealand  Year Month  Quarter
Period
Q1 1960        7.5      44.8764  1960  None        1
Q1 1961        7.8      45.5819  1961  None        1
Q1 1962        7.8      46.9145  1962  None        1
Q1 1963        7.8      47.7767  1963  None        1
Q1 1964        8.0      48.9917  1964  None        1

In [52]:
new_month_df = year_to_int(new_month_df)
new_month_df.dtypes

Country
Austria           float64
Belgium           float64
Brazil            float64
Bulgaria          float64
Canada            float64
Chile             float64
China             float64
Colombia          float64
Croatia           float64
Cyprus            float64
Czech-Republic    float64
Denmark           float64
Estonia           float64
Finland           float64
France            float64
Germany           float64
Greece            float64
Hong-Kong         float64
Hungary           float64
Iceland           float64
India             float64
Indonesia         float64
Ireland           float64
Israel            float64
Italy             float64
Japan             float64
Latvia            float64
Lithuania         float64
Luxembourg        float64
Macedonia         float64
Malaysia          float64
Malta             float64
Mexico            float64
Morocco           float64
Netherlands       float64
Norway            float64
Peru              float64
Philippines       float64
Poland            float64
Portugal          float64
Romania           float64
Russia            float64
Serbia            float64
Singapore         float64
Slovakia          float64
Slovenia          float64
South-Africa      float64
South-Korea       float64
Spain             float64
Sweden            float64
Switzerland       float64
Thailand          float64
Turkey            float64
USA               float64
United-Kingdom    float64
Paraguay          float64
Year                Int64
Month              object
Quarter             int64
dtype: object

In [55]:
new_month_df.tail()

Country,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,Colombia,Croatia,Cyprus,...,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom,Paraguay,Year,Month,Quarter
Period,,,,,,,,,,,,,,,,,,,,,
Sep 2020,108.67,108.21,5391.75,105.70,136.9,79.72,127.9984,105.29,103.18,99.70,...,108.06,100.44,102.18,182.90,260.280,109.1,106.6,2020,Sep,3
Sep 2021,112.23,112.35,5944.21,109.92,142.9,83.98,128.4814,110.04,106.80,103.31,...,111.29,101.29,101.21,218.71,274.310,112.4,113.4,2021,Sep,3
Sep 2022,124.58,125.90,6370.34,127.10,152.7,95.51,131.9948,122.63,120.21,112.63,...,122.70,104.53,107.70,401.10,296.808,122.3,124.0,2022,Sep,3
Sep 2023,131.75,126.73,6700.66,135.18,158.5,100.39,132.1184,136.11,129.15,117.48,...,127.19,106.57,108.02,648.45,307.789,130.1,128.3,2023,Sep,3
Sep 2024,134.13,132.21,6997.15,137.25,161.1,104.54,132.7618,144.02,133.11,119.41,...,128.76,107.50,108.68,969.11,315.301,133.5,133.5,2024,Sep,3

In [56]:
# save as parquet file
new_quarter_df.to_parquet("../../data/quarter_cpi_values.parquet", index=False)

In [58]:
# save as parquet file
new_month_df.to_parquet("../../data/month_cpi_values.parquet", index=False)