In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import os

### Prove 01
- Prove that statistics data for country are raw and unalterated

In [2]:
peru_df = pd.read_parquet("../data/by_country/Peru_macro_profile.parquet")

In [3]:
peru_df

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,16.2375,NaN,79.9225,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,21.2400,NaN,88.6650,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,21.3000,NaN,91.6675,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,26.3100,NaN,105.3950,NaN,NaN,100.0025
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,28.1750,NaN,117.9975,NaN,NaN,120.4325
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,32.8375,74.703275,127.4400,NaN,NaN,143.1275
6,2013,NaN,NaN,NaN,NaN,NaN,66.965000,36.5375,76.769950,137.1725,NaN,NaN,162.8475
7,2014,NaN,NaN,NaN,NaN,NaN,64.422500,37.2975,79.389508,144.6225,225.785000,NaN,172.3575
8,2015,NaN,99.3,19.00,NaN,20.5125,61.294167,37.6300,82.089392,153.5625,245.164167,NaN,167.4675
9,2016,17.65,102.9,18.75,77.54,21.6150,61.033333,37.8925,85.009067,165.6975,258.812500,3.74,164.1850
10,2017,17.65,105.6,18.95,77.72,22.9625,62.995000,38.2800,87.554517,176.5600,272.985000,3.69,168.0050
11,2018,18.12,111.3,18.82,77.91,24.0950,60.379167,41.4675,88.876058,187.0250,296.094167,3.49,168.4150
12,2019,18.60,119.9,18.64,78.10,25.5900,66.122500,43.6700,90.877217,194.3825,319.730833,3.38,172.0325
13,2020,16.86,117.8,19.13,78.30,28.0475,72.015000,37.8775,92.698158,183.5025,357.590000,7.18,173.6700
14,2021,17.85,120.2,19.61,78.50,30.3375,75.641667,55.0350,96.657225,222.9525,387.834167,5.10,173.6000
15,2022,18.26,123.1,19.05,78.71,31.7775,74.797500,59.1025,104.713167,237.9250,408.460833,3.85,172.6475
16,2023,18.58,NaN,NaN,78.92,34.5475,72.938333,57.1800,111.473042,254.3525,415.464167,4.90,175.1550
17,2024,NaN,NaN,NaN,NaN,36.7100,76.992500,61.1500,113.774933,276.6325,417.818333,4.83,175.3775

### Prove 02
- Load the new statistics data
- Prove that are the same countries for each statistic

In [4]:
# Load Parquet file
rule_of_law_df = pd.read_parquet('../data/image_data/wb_ruleoflaw.parquet')
share_of_industry_df = pd.read_parquet('../data/image_data/Share_of_industry.parquet')
tax_revenue_df = pd.read_parquet('../data/image_data/Tax_revenue.parquet')
inflation_df = pd.read_parquet('../data/image_data/Inflation.parquet')
edu_spending_df = pd.read_parquet('../data/image_data/Education_spending.parquet')
govermment_effective_df = pd.read_parquet('../data/image_data/wb_government_effectiveness.parquet')

In [5]:
name_df = [
    'rule_of_law_df', 'share_of_industry_df', 'tax_revenue_df', 'inflation_df', 'edu_spending_df', 'govermment_effective_df'
]

In [6]:
list_df = [
    rule_of_law_df, share_of_industry_df, tax_revenue_df, inflation_df, edu_spending_df, govermment_effective_df
]

In [7]:
def count_columns_per_df(dfs, names=None):
    """
    Returns the number of columns (countries) in each DataFrame.
    """
    if names is None:
        names = [f'DataFrame {i+1}' for i in range(len(dfs))]
    
    summary = []
    for name, df in zip(names, dfs):
        summary.append((name, df.shape[1]))
    
    print("\nColumn Count Summary")
    print(f"{'DataFrame':<25} {'# Columns':>10}")
    print("-" * 40)
    for name, count in summary:
        print(f"{name:<25} {count:>10}")

In [8]:
def compare_columns(df1, df2):
    # Get the set of column names from each DataFrame
    columns_df1 = set(df1.columns)
    columns_df2 = set(df2.columns)

    # Find columns that exist in both DataFrames
    in_both = columns_df1 & columns_df2

    # Find columns that exist only in df1
    only_in_df1 = columns_df1 - columns_df2

    # Find columns that exist only in df2
    only_in_df2 = columns_df2 - columns_df1

    # Return a dictionary with sorted lists of column names
    return {
        "in_both": sorted(in_both),
        "only_in_df1": sorted(only_in_df1),
        "only_in_df2": sorted(only_in_df2)
    }

In [9]:
count_columns_per_df(list_df, name_df)

Column Count Summary
DataFrame                  # Columns
----------------------------------------
rule_of_law_df                    58
share_of_industry_df              58
tax_revenue_df                    58
inflation_df                      58
edu_spending_df                   58
govermment_effective_df           58

In [10]:
compare_columns(rule_of_law_df, share_of_industry_df)

{'in_both': ['Australia',
  'Austria',
  'Belgium',
  'Brazil',
  'Bulgaria',
  'Canada',
  'Chile',
  'China',
  'Colombia',
  'Croatia',
  'Cyprus',
  'Czech-Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Germany',
  'Greece',
  'Hong-Kong',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Ireland',
  'Israel',
  'Italy',
  'Japan',
  'Latvia',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Malaysia',
  'Malta',
  'Mexico',
  'Morocco',
  'Netherlands',
  'New-Zealand',
  'Norway',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'Serbia',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'South-Africa',
  'South-Korea',
  'Spain',
  'Sweden',
  'Switzerland',
  'Thailand',
  'Turkey',
  'USA',
  'United-Kingdom'],
 'only_in_df1': [],
 'only_in_df2': []}

### Porve 03
- Prove the index in the data frames
- If the index is the year change to the standard
- This for merge with other df's

In [11]:
rule_of_law_df.head()

,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,Colombia,Croatia,...,Slovenia,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom
2016,1.72,1.76,1.39,-0.31,-0.14,1.80,0.96,-0.32,-0.27,0.34,...,1.05,-0.16,1.13,0.97,1.95,1.91,0.01,-0.34,1.58,1.64
2017,1.65,1.80,1.32,-0.31,-0.12,1.76,0.98,-0.26,-0.37,0.31,...,0.99,-0.16,1.13,1.02,1.82,1.89,0.01,-0.32,1.61,1.65
2018,1.67,1.85,1.34,-0.30,-0.11,1.72,0.94,-0.19,-0.38,0.30,...,1.02,-0.22,1.20,0.98,1.78,1.89,0.00,-0.39,1.48,1.60
2019,1.69,1.86,1.34,-0.22,-0.04,1.72,0.92,-0.26,-0.39,0.35,...,1.09,-0.19,1.16,0.99,1.79,1.86,0.09,-0.35,1.42,1.57
2020,1.62,1.77,1.33,-0.23,-0.13,1.62,0.93,-0.10,-0.49,0.24,...,1.04,-0.24,1.15,0.86,1.77,1.78,0.11,-0.42,1.34,1.46

In [12]:
rule_of_law_df = rule_of_law_df.reset_index().rename(columns={"index": "Year"})
share_of_industry_df = share_of_industry_df.reset_index().rename(columns={"index": "Year"})
tax_revenue_df = tax_revenue_df.reset_index().rename(columns={"index": "Year"})
inflation_df = inflation_df.reset_index().rename(columns={"index": "Year"})
edu_spending_df = edu_spending_df.reset_index().rename(columns={"index": "Year"})
govermment_effective_df = govermment_effective_df.reset_index().rename(columns={"index": "Year"})

In [13]:
list_df = [
    rule_of_law_df, share_of_industry_df, tax_revenue_df, inflation_df, edu_spending_df, govermment_effective_df
]

### Prove 04
- Prove that the lapses in year for each new statistic are the same or not

In [14]:
def get_year_ranges(list_of_dfs, names=None):
    """
    list_of_dfs: list of DataFrames with a 'Year' column
    names: optional list of names for each DataFrame
    """
    # If no names are provided, generate default names
    if names is None:
        names = [f"DataFrame_{i+1}" for i in range(len(list_of_dfs))]

    summary = []

    # Iterate through each DataFrame and its corresponding name
    for name, df in zip(names, list_of_dfs):
        if "Year" in df.columns:
            years = df["Year"].dropna()
            if not years.empty:
                summary.append({
                    "Indicator": name,
                    "Start Year": int(years.min()),
                    "End Year": int(years.max())
                })
            else:
                summary.append({
                    "Indicator": name,
                    "Start Year": None,
                    "End Year": None
                })
        else:
            summary.append({
                "Indicator": name,
                "Start Year": "❌ Missing 'Year' column",
                "End Year": "❌ Missing 'Year' column"
            })

    return pd.DataFrame(summary)

In [15]:
get_year_ranges(list_df, name_df)

                 Indicator  Start Year  End Year
0           rule_of_law_df        2016      2023
1     share_of_industry_df        2016      2024
2           tax_revenue_df        2015      2023
3             inflation_df        2017      2024
4          edu_spending_df        2010      2023
5  govermment_effective_df        2016      2023

In [16]:
count_columns_per_df(list_df, name_df)

Column Count Summary
DataFrame                  # Columns
----------------------------------------
rule_of_law_df                    59
share_of_industry_df              59
tax_revenue_df                    59
inflation_df                      59
edu_spending_df                   59
govermment_effective_df           59

### Prove 05
- Prove that the countries for each new statistic are the same that we have in the directory for the macroeconomics for countries

In [17]:
def check_columns_in_filenames(dataframes, df_names, path):
    """
    Checks whether column names from each DataFrame exist in the filenames of a given path,
    accounting for differences like '-' in column names vs '_' in filenames.

    Parameters:
    - dataframes: list of pandas DataFrames
    - df_names: list of names corresponding to each DataFrame
    - path: directory path containing files

    Prints:
    - For each DataFrame, its name followed by the list of column names
      that do NOT appear in any of the filenames in the specified path.
    """
    try:
        filenames = os.listdir(path)
    except FileNotFoundError:
        print(f"❌ Path not found: {path}")
        return

    # Normalize filenames: lowercase and replace underscores with hyphens
    normalized_filenames = [f.lower().replace("_", "-") for f in filenames]

    for df, name in zip(dataframes, df_names):
        missing_columns = []
        for col in df.columns:
            normalized_col = col.lower().replace("_", "-")
            if not any(normalized_col in fname for fname in normalized_filenames):
                missing_columns.append(col)

        print(f"📊 DataFrame: {name}")
        if missing_columns:
            print(f"   ❌ Columns not found in filenames: {missing_columns}")
        else:
            print("   ✅ All columns found in filenames")

In [18]:
check_columns_in_filenames(list_df, name_df, '../data/by_country')

📊 DataFrame: rule_of_law_df
   ❌ Columns not found in filenames: ['Year', 'China', 'Indonesia', 'Macedonia', 'Morocco']
📊 DataFrame: share_of_industry_df
   ❌ Columns not found in filenames: ['Year', 'China', 'Indonesia', 'Macedonia', 'Morocco']
📊 DataFrame: tax_revenue_df
   ❌ Columns not found in filenames: ['Year', 'China', 'Indonesia', 'Macedonia', 'Morocco']
📊 DataFrame: inflation_df
   ❌ Columns not found in filenames: ['Year', 'China', 'Indonesia', 'Macedonia', 'Morocco']
📊 DataFrame: edu_spending_df
   ❌ Columns not found in filenames: ['Year', 'China', 'Indonesia', 'Macedonia', 'Morocco']
📊 DataFrame: govermment_effective_df
   ❌ Columns not found in filenames: ['Year', 'China', 'Indonesia', 'Macedonia', 'Morocco']

In [19]:
def remove_columns(df, columns_to_remove):
    """
    Removes specific columns from a DataFrame.

    Parameters:
    - df: Original DataFrame
    - columns_to_remove: list of column names to remove

    Returns:
    - DataFrame without the specified columns
    """
    return df.drop(columns=columns_to_remove, errors='ignore')

In [21]:
# countries to delete
delete_countries = ['China', 'Morocco', 'Macedonia', 'Indonesia']

rule_of_law_df = remove_columns(rule_of_law_df, delete_countries)
share_of_industry_df = remove_columns(share_of_industry_df, delete_countries)
tax_revenue_df = remove_columns(tax_revenue_df, delete_countries)
inflation_df = remove_columns(inflation_df, delete_countries)
edu_spending_df = remove_columns(edu_spending_df, delete_countries)
govermment_effective_df = remove_columns(govermment_effective_df, delete_countries)

In [22]:
new_df_list = [
    rule_of_law_df,
    share_of_industry_df,
    tax_revenue_df,
    inflation_df,
    edu_spending_df,
    govermment_effective_df
]

count_columns_per_df(new_df_list, name_df)

Column Count Summary
DataFrame                  # Columns
----------------------------------------
rule_of_law_df                    55
share_of_industry_df              55
tax_revenue_df                    55
inflation_df                      55
edu_spending_df                   55
govermment_effective_df           55

### Prove 06
- Prove that now there is the same countries in the new statistics and in the country directory

In [23]:
check_columns_in_filenames(new_df_list, name_df, '../data/by_country')

📊 DataFrame: rule_of_law_df
   ❌ Columns not found in filenames: ['Year']
📊 DataFrame: share_of_industry_df
   ❌ Columns not found in filenames: ['Year']
📊 DataFrame: tax_revenue_df
   ❌ Columns not found in filenames: ['Year']
📊 DataFrame: inflation_df
   ❌ Columns not found in filenames: ['Year']
📊 DataFrame: edu_spending_df
   ❌ Columns not found in filenames: ['Year']
📊 DataFrame: govermment_effective_df
   ❌ Columns not found in filenames: ['Year']

### Prove 07
- Prove that we can add the new macroeconomic to each country parquet file

In [24]:
def update_country_parquets_by_name_match(macro_dict, output_path):
    os.makedirs(output_path, exist_ok=True)
    existing_files = [f for f in os.listdir(output_path) if f.endswith('.parquet')]

    for indicator, df in macro_dict.items():
        for country in df.columns:
            if country == 'Year':
                continue

            # Extraer columna del país y renombrar con el indicador
            country_data = df[['Year', country]].copy()
            country_data.rename(columns={country: indicator}, inplace=True)

            # Buscar archivo que contenga el nombre del país
            matched_file = next((f for f in existing_files if country in f), None)

            if matched_file:
                file_path = os.path.join(output_path, matched_file)
                existing_df = pd.read_parquet(file_path)
                updated_df = pd.merge(existing_df, country_data, on='Year', how='outer')
            else:
                updated_df = country_data
                file_path = os.path.join(output_path, f"{country}_data.parquet")  # Nombre genérico

            updated_df.sort_values(by='Year', inplace=True)
            updated_df.to_parquet(file_path, index=False)

In [26]:
macro_dict = {
    'rule_of_law_df': rule_of_law_df,
    'share_of_industry_df': share_of_industry_df,
    'tax_revenue_df': tax_revenue_df,
    'inflation_df': inflation_df,
    'edu_spending_df': edu_spending_df,
    'govermment_effective_df': govermment_effective_df
}

In [27]:
update_country_parquets_by_name_match(macro_dict, '../data/by_country')

### Prove 08
- Prove that all was smooth
- Prove that our hope do not paly against us, we say this because we do not have an backup for the country directory

In [28]:
peru_df = pd.read_parquet("../data/by_country/Peru_macro_profile.parquet")

In [30]:
peru_df

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price,rule_of_law_df,share_of_industry_df,tax_revenue_df,inflation_df,edu_spending_df,govermment_effective_df
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,16.2375,NaN,79.9225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,21.2400,NaN,88.6650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,21.3000,NaN,91.6675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,26.3100,NaN,105.3950,NaN,NaN,100.0025,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,28.1750,NaN,117.9975,NaN,NaN,120.4325,NaN,NaN,NaN,NaN,NaN,NaN
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,32.8375,74.703275,127.4400,NaN,NaN,143.1275,NaN,NaN,NaN,NaN,NaN,NaN
6,2013,NaN,NaN,NaN,NaN,NaN,66.965000,36.5375,76.769950,137.1725,NaN,NaN,162.8475,NaN,NaN,NaN,NaN,NaN,NaN
7,2014,NaN,NaN,NaN,NaN,NaN,64.422500,37.2975,79.389508,144.6225,225.785000,NaN,172.3575,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,NaN,99.3,19.00,NaN,20.5125,61.294167,37.6300,82.089392,153.5625,245.164167,NaN,167.4675,NaN,NaN,14.91,NaN,NaN,NaN
9,2016,17.65,102.9,18.75,77.54,21.6150,61.033333,37.8925,85.009067,165.6975,258.812500,3.74,164.1850,-0.50,NaN,13.78,NaN,3.81,-0.26
10,2017,17.65,105.6,18.95,77.72,22.9625,62.995000,38.2800,87.554517,176.5600,272.985000,3.69,168.0050,-0.52,31.30,13.17,3.0,3.93,-0.20
11,2018,18.12,111.3,18.82,77.91,24.0950,60.379167,41.4675,88.876058,187.0250,296.094167,3.49,168.4150,-0.57,31.62,14.28,1.5,3.71,-0.32
12,2019,18.60,119.9,18.64,78.10,25.5900,66.122500,43.6700,90.877217,194.3825,319.730833,3.38,172.0325,-0.52,30.45,14.52,2.3,3.82,-0.13
13,2020,16.86,117.8,19.13,78.30,28.0475,72.015000,37.8775,92.698158,183.5025,357.590000,7.18,173.6700,-0.38,30.32,13.22,2.0,4.26,-0.29
14,2021,17.85,120.2,19.61,78.50,30.3375,75.641667,55.0350,96.657225,222.9525,387.834167,5.10,173.6000,-0.53,35.74,15.92,4.3,3.93,-0.30
15,2022,18.26,123.1,19.05,78.71,31.7775,74.797500,59.1025,104.713167,237.9250,408.460833,3.85,172.6475,-0.55,34.93,NaN,8.3,3.83,-0.40
16,2023,18.58,NaN,NaN,78.92,34.5475,72.938333,57.1800,111.473042,254.3525,415.464167,4.90,175.1550,-0.54,33.97,NaN,6.5,4.24,-0.49
17,2024,NaN,NaN,NaN,NaN,36.7100,76.992500,61.1500,113.774933,276.6325,417.818333,4.83,175.3775,NaN,32.24,NaN,2.0,NaN,NaN

- All good

In [32]:
peru_df.dtypes

Year                         Int64
labor_force                float64
livestock_prod             float64
agr_land                   float64
urban_pop                  float64
gov_exp                    float64
reserves                   float64
investment                 float64
cpi                        float64
gdp                        float64
priv_cred                  float64
unemployment               float64
house_price                float64
rule_of_law_df             float64
share_of_industry_df       float64
tax_revenue_df             float64
inflation_df               float64
edu_spending_df            float64
govermment_effective_df    float64
dtype: object