In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [58]:
df_countries_hpi = pd.read_parquet('../data/clean_hpi.parquet')
df_countries_hpi.head()

,Year,Australia,Austria,Belgium,Brazil,Bulgaria,Canada,Chile,China,Colombia,...,Slovenia,South-Africa,South-Korea,Spain,Sweden,Switzerland,Thailand,Turkey,USA,United-Kingdom
0,2010,100.0000,100.0000,100.0000,100.0000,100.0000,100.0000,99.9975,100.0025,100.0000,...,99.9975,100.0000,99.9975,100.0025,100.0025,100.0000,100.0000,100.0000,100.00,100.0000
1,2011,97.8450,104.2250,103.5825,119.0225,94.4900,105.7500,112.2300,104.1175,107.8900,...,102.7150,103.5900,105.2275,92.3550,102.5800,107.5100,104.2625,108.8000,97.24,98.5450
2,2012,97.5325,117.1325,106.0150,133.0600,92.6900,110.6150,124.0250,103.4225,118.7925,...,95.6325,108.4075,108.2500,78.7075,103.8650,113.7225,107.6325,120.6750,101.82,98.9200
3,2013,103.9925,122.5900,107.5900,145.3175,90.6500,112.7600,136.5175,109.5550,130.0650,...,90.6200,115.4075,107.8000,71.5250,109.2225,118.3000,115.9925,134.4625,111.83,101.4550
4,2014,113.4075,126.7900,107.2250,155.3575,91.9475,118.8625,154.7200,112.3775,140.7525,...,84.6400,123.9875,109.4325,71.7450,119.5200,121.4650,127.0725,151.2500,118.88,109.6025

In [18]:
df_clusters = pd.read_parquet('../data/clusters/clusters_kmean_random.parquet')
df_clusters.head()

     Country iso_a3  cluster
0  Australia    AUS        1
1    Austria    AUT        0
2    Belgium    BEL        0
3     Brazil    BRA        1
4   Bulgaria    BGR        0

In [4]:
df_clusters.shape

(53, 3)

In [7]:
import geopandas as gpd

In [8]:
world = gpd.read_file("../data/geo_data/ne_110m_admin_0_countries.shp")
world.head()

,featurecla,scalerank,LABELRANK,SOVEREIGNT,SOV_A3,ADM0_DIF,LEVEL,TYPE,TLC,ADMIN,...,FCLASS_TR,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,geometry
0,Admin-0 country,1,6,Fiji,FJI,0,2,Sovereign country,1,Fiji,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((180 -16.06713, 180 -16.55522, ..."
1,Admin-0 country,1,3,United Republic of Tanzania,TZA,0,2,Sovereign country,1,United Republic of Tanzania,...,None,None,None,None,None,None,None,None,None,"POLYGON ((33.90371 -0.95, 34.07262 -1.05982, 3..."
2,Admin-0 country,1,7,Western Sahara,SAH,0,2,Indeterminate,1,Western Sahara,...,Unrecognized,Unrecognized,Unrecognized,None,None,Unrecognized,None,None,None,"POLYGON ((-8.66559 27.65643, -8.66512 27.58948..."
3,Admin-0 country,1,2,Canada,CAN,0,2,Sovereign country,1,Canada,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((-122.84 49, -122.97421 49.0025..."
4,Admin-0 country,1,2,United States of America,US1,1,2,Country,1,United States of America,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((-122.84 49, -120 49, -117.0312..."

In [9]:
print(list(world.columns))

['featurecla', 'scalerank', 'LABELRANK', 'SOVEREIGNT', 'SOV_A3', 'ADM0_DIF', 'LEVEL', 'TYPE', 'TLC', 'ADMIN', 'ADM0_A3', 'GEOU_DIF', 'GEOUNIT', 'GU_A3', 'SU_DIF', 'SUBUNIT', 'SU_A3', 'BRK_DIFF', 'NAME', 'NAME_LONG', 'BRK_A3', 'BRK_NAME', 'BRK_GROUP', 'ABBREV', 'POSTAL', 'FORMAL_EN', 'FORMAL_FR', 'NAME_CIAWF', 'NOTE_ADM0', 'NOTE_BRK', 'NAME_SORT', 'NAME_ALT', 'MAPCOLOR7', 'MAPCOLOR8', 'MAPCOLOR9', 'MAPCOLOR13', 'POP_EST', 'POP_RANK', 'POP_YEAR', 'GDP_MD', 'GDP_YEAR', 'ECONOMY', 'INCOME_GRP', 'FIPS_10', 'ISO_A2', 'ISO_A2_EH', 'ISO_A3', 'ISO_A3_EH', 'ISO_N3', 'ISO_N3_EH', 'UN_A3', 'WB_A2', 'WB_A3', 'WOE_ID', 'WOE_ID_EH', 'WOE_NOTE', 'ADM0_ISO', 'ADM0_DIFF', 'ADM0_TLC', 'ADM0_A3_US', 'ADM0_A3_FR', 'ADM0_A3_RU', 'ADM0_A3_ES', 'ADM0_A3_CN', 'ADM0_A3_TW', 'ADM0_A3_IN', 'ADM0_A3_NP', 'ADM0_A3_PK', 'ADM0_A3_DE', 'ADM0_A3_GB', 'ADM0_A3_BR', 'ADM0_A3_IL', 'ADM0_A3_PS', 'ADM0_A3_SA', 'ADM0_A3_EG', 'ADM0_A3_MA', 'ADM0_A3_PT', 'ADM0_A3_AR', 'ADM0_A3_JP', 'ADM0_A3_KO', 'ADM0_A3_VN', 'ADM0_A3_TR', 'ADM0_A3_ID', 'ADM0_A3_PL', 'ADM0_A3_GR', 'ADM0_A3_IT', 'ADM0_A3_NL', 'ADM0_A3_SE', 'ADM0_A3_BD', 'ADM0_A3_UA', 'ADM0_A3_UN', 'ADM0_A3_WB', 'CONTINENT', 'REGION_UN', 'SUBREGION', 'REGION_WB', 'NAME_LEN', 'LONG_LEN', 'ABBREV_LEN', 'TINY', 'HOMEPART', 'MIN_ZOOM', 'MIN_LABEL', 'MAX_LABEL', 'LABEL_X', 'LABEL_Y', 'NE_ID', 'WIKIDATAID', 'NAME_AR', 'NAME_BN', 'NAME_DE', 'NAME_EN', 'NAME_ES', 'NAME_FA', 'NAME_FR', 'NAME_EL', 'NAME_HE', 'NAME_HI', 'NAME_HU', 'NAME_ID', 'NAME_IT', 'NAME_JA', 'NAME_KO', 'NAME_NL', 'NAME_PL', 'NAME_PT', 'NAME_RU', 'NAME_SV', 'NAME_TR', 'NAME_UK', 'NAME_UR', 'NAME_VI', 'NAME_ZH', 'NAME_ZHT', 'FCLASS_ISO', 'TLC_DIFF', 'FCLASS_TLC', 'FCLASS_US', 'FCLASS_FR', 'FCLASS_RU', 'FCLASS_ES', 'FCLASS_CN', 'FCLASS_TW', 'FCLASS_IN', 'FCLASS_NP', 'FCLASS_PK', 'FCLASS_DE', 'FCLASS_GB', 'FCLASS_BR', 'FCLASS_IL', 'FCLASS_PS', 'FCLASS_SA', 'FCLASS_EG', 'FCLASS_MA', 'FCLASS_PT', 'FCLASS_AR', 'FCLASS_JP', 'FCLASS_KO', 'FCLASS_VN', 'FCLASS_TR', 'FCLASS_ID', 'FCLASS_PL', 'FCLASS_GR', 'FCLASS_IT', 'FCLASS_NL', 'FCLASS_SE', 'FCLASS_BD', 'FCLASS_UA', 'geometry']

In [20]:
df_clusters = df_clusters.merge(
    world[['ISO_A3', 'CONTINENT']],
    left_on='iso_a3',
    right_on='ISO_A3',
    how='left')
df_clusters.head()

     Country iso_a3  cluster ISO_A3      CONTINENT
0  Australia    AUS        1    AUS        Oceania
1    Austria    AUT        0    AUT         Europe
2    Belgium    BEL        0    BEL         Europe
3     Brazil    BRA        1    BRA  South America
4   Bulgaria    BGR        0    BGR         Europe

In [21]:
df_clusters.drop(columns=['ISO_A3'], inplace=True)

In [22]:
df_clusters.tail()

           Country iso_a3  cluster      CONTINENT
48     Switzerland    CHE        1         Europe
49        Thailand    THA        1           Asia
50          Turkey    TUR        1           Asia
51  United Kingdom    GBR        1         Europe
52             USA    USA        1  North America

In [24]:
df_clusters

           Country iso_a3  cluster      CONTINENT
0        Australia    AUS        1        Oceania
1          Austria    AUT        0         Europe
2          Belgium    BEL        0         Europe
3           Brazil    BRA        1  South America
4         Bulgaria    BGR        0         Europe
5           Canada    CAN        1  North America
6            Chile    CHL        2  South America
7         Colombia    COL        2  South America
8          Croatia    HRV        0         Europe
9           Cyprus    CYP        0           Asia
10           Czech    CZE        1         Europe
11         Denmark    DNK        1         Europe
12         Estonia    EST        0         Europe
13         Finland    FIN        0         Europe
14          France    FRA        1            NaN
15         Germany    DEU        1         Europe
16          Greece    GRC        0         Europe
17         Hungary    HUN        1         Europe
18         Iceland    ISL        1         Europe
19           India    IND        2           Asia
20         Ireland    IRL        0         Europe
21          Israel    ISR        1           Asia
22           Italy    ITA        1         Europe
23           Japan    JPN        2           Asia
24          Latvia    LVA        0         Europe
25       Lithuania    LTU        0         Europe
26      Luxembourg    LUX        0         Europe
27        Malaysia    MYS        1           Asia
28           Malta    MLT        0            NaN
29          Mexico    MEX        1  North America
30     Netherlands    NLD        1         Europe
31     New Zealand    NZL        0        Oceania
32          Norway    NOR        1            NaN
33        Paraguay    PRY        2  South America
34            Peru    PER        1  South America
35     Philippines    PHL        1           Asia
36          Poland    POL        1         Europe
37        Portugal    PRT        0         Europe
38         Romania    ROU        1         Europe
39          Russia    RUS        2         Europe
40          Serbia    SRB        1         Europe
41       Singapore    SGP        1            NaN
42        Slovakia    SVK        0         Europe
43        Slovenia    SVN        0         Europe
44    South Africa    ZAF        1         Africa
45     South Korea    KOR        2           Asia
46           Spain    ESP        1         Europe
47          Sweden    SWE        1         Europe
48     Switzerland    CHE        1         Europe
49        Thailand    THA        1           Asia
50          Turkey    TUR        1           Asia
51  United Kingdom    GBR        1         Europe
52             USA    USA        1  North America

In [28]:
world[world['ISO_A3'] == 'SGP']['CONTINENT']

Series([], Name: CONTINENT, dtype: object)

In [29]:
world[world['ISO_A3'] == 'USA']['CONTINENT']

4    North America
Name: CONTINENT, dtype: object

In [31]:
world[world['ISO_A3'] == 'FRA']

Empty GeoDataFrame
Columns: [featurecla, scalerank, LABELRANK, SOVEREIGNT, SOV_A3, ADM0_DIF, LEVEL, TYPE, TLC, ADMIN, ADM0_A3, GEOU_DIF, GEOUNIT, GU_A3, SU_DIF, SUBUNIT, SU_A3, BRK_DIFF, NAME, NAME_LONG, BRK_A3, BRK_NAME, BRK_GROUP, ABBREV, POSTAL, FORMAL_EN, FORMAL_FR, NAME_CIAWF, NOTE_ADM0, NOTE_BRK, NAME_SORT, NAME_ALT, MAPCOLOR7, MAPCOLOR8, MAPCOLOR9, MAPCOLOR13, POP_EST, POP_RANK, POP_YEAR, GDP_MD, GDP_YEAR, ECONOMY, INCOME_GRP, FIPS_10, ISO_A2, ISO_A2_EH, ISO_A3, ISO_A3_EH, ISO_N3, ISO_N3_EH, UN_A3, WB_A2, WB_A3, WOE_ID, WOE_ID_EH, WOE_NOTE, ADM0_ISO, ADM0_DIFF, ADM0_TLC, ADM0_A3_US, ADM0_A3_FR, ADM0_A3_RU, ADM0_A3_ES, ADM0_A3_CN, ADM0_A3_TW, ADM0_A3_IN, ADM0_A3_NP, ADM0_A3_PK, ADM0_A3_DE, ADM0_A3_GB, ADM0_A3_BR, ADM0_A3_IL, ADM0_A3_PS, ADM0_A3_SA, ADM0_A3_EG, ADM0_A3_MA, ADM0_A3_PT, ADM0_A3_AR, ADM0_A3_JP, ADM0_A3_KO, ADM0_A3_VN, ADM0_A3_TR, ADM0_A3_ID, ADM0_A3_PL, ADM0_A3_GR, ADM0_A3_IT, ADM0_A3_NL, ADM0_A3_SE, ADM0_A3_BD, ADM0_A3_UA, ADM0_A3_UN, ADM0_A3_WB, CONTINENT, REGION_UN, SUBREGION, REGION_WB, NAME_LEN, LONG_LEN, ABBREV_LEN, TINY, ...]
Index: []

[0 rows x 169 columns]

In [32]:
world[world['ISO_A3'] == 'USA']

,featurecla,scalerank,LABELRANK,SOVEREIGNT,SOV_A3,ADM0_DIF,LEVEL,TYPE,TLC,ADMIN,...,FCLASS_TR,FCLASS_ID,FCLASS_PL,FCLASS_GR,FCLASS_IT,FCLASS_NL,FCLASS_SE,FCLASS_BD,FCLASS_UA,geometry
4,Admin-0 country,1,2,United States of America,US1,1,2,Country,1,United States of America,...,None,None,None,None,None,None,None,None,None,"MULTIPOLYGON (((-122.84 49, -120 49, -117.0312..."

In [33]:
df_clusters.loc[df_clusters['iso_a3'] == 'FRA', 'CONTINENT'] = 'Europe'
df_clusters.loc[df_clusters['iso_a3'] == 'MLT', 'CONTINENT'] = 'Europe'
df_clusters.loc[df_clusters['iso_a3'] == 'NOR', 'CONTINENT'] = 'Europe'
df_clusters.loc[df_clusters['iso_a3'] == 'SGP', 'CONTINENT'] = 'Asia'

In [34]:
df_clusters.isna()

    Country  iso_a3  cluster  CONTINENT
0     False   False    False      False
1     False   False    False      False
2     False   False    False      False
3     False   False    False      False
4     False   False    False      False
5     False   False    False      False
6     False   False    False      False
7     False   False    False      False
8     False   False    False      False
9     False   False    False      False
10    False   False    False      False
11    False   False    False      False
12    False   False    False      False
13    False   False    False      False
14    False   False    False      False
15    False   False    False      False
16    False   False    False      False
17    False   False    False      False
18    False   False    False      False
19    False   False    False      False
20    False   False    False      False
21    False   False    False      False
22    False   False    False      False
23    False   False    False      False
24    False   False    False      False
25    False   False    False      False
26    False   False    False      False
27    False   False    False      False
28    False   False    False      False
29    False   False    False      False
30    False   False    False      False
31    False   False    False      False
32    False   False    False      False
33    False   False    False      False
34    False   False    False      False
35    False   False    False      False
36    False   False    False      False
37    False   False    False      False
38    False   False    False      False
39    False   False    False      False
40    False   False    False      False
41    False   False    False      False
42    False   False    False      False
43    False   False    False      False
44    False   False    False      False
45    False   False    False      False
46    False   False    False      False
47    False   False    False      False
48    False   False    False      False
49    False   False    False      False
50    False   False    False      False
51    False   False    False      False
52    False   False    False      False

In [36]:
world[world['NAME_EN'] == 'France']['ISO_A3']

43    -99
Name: ISO_A3, dtype: object

In [38]:
world[world['NAME_EN'] == 'Singapore']

Empty GeoDataFrame
Columns: [featurecla, scalerank, LABELRANK, SOVEREIGNT, SOV_A3, ADM0_DIF, LEVEL, TYPE, TLC, ADMIN, ADM0_A3, GEOU_DIF, GEOUNIT, GU_A3, SU_DIF, SUBUNIT, SU_A3, BRK_DIFF, NAME, NAME_LONG, BRK_A3, BRK_NAME, BRK_GROUP, ABBREV, POSTAL, FORMAL_EN, FORMAL_FR, NAME_CIAWF, NOTE_ADM0, NOTE_BRK, NAME_SORT, NAME_ALT, MAPCOLOR7, MAPCOLOR8, MAPCOLOR9, MAPCOLOR13, POP_EST, POP_RANK, POP_YEAR, GDP_MD, GDP_YEAR, ECONOMY, INCOME_GRP, FIPS_10, ISO_A2, ISO_A2_EH, ISO_A3, ISO_A3_EH, ISO_N3, ISO_N3_EH, UN_A3, WB_A2, WB_A3, WOE_ID, WOE_ID_EH, WOE_NOTE, ADM0_ISO, ADM0_DIFF, ADM0_TLC, ADM0_A3_US, ADM0_A3_FR, ADM0_A3_RU, ADM0_A3_ES, ADM0_A3_CN, ADM0_A3_TW, ADM0_A3_IN, ADM0_A3_NP, ADM0_A3_PK, ADM0_A3_DE, ADM0_A3_GB, ADM0_A3_BR, ADM0_A3_IL, ADM0_A3_PS, ADM0_A3_SA, ADM0_A3_EG, ADM0_A3_MA, ADM0_A3_PT, ADM0_A3_AR, ADM0_A3_JP, ADM0_A3_KO, ADM0_A3_VN, ADM0_A3_TR, ADM0_A3_ID, ADM0_A3_PL, ADM0_A3_GR, ADM0_A3_IT, ADM0_A3_NL, ADM0_A3_SE, ADM0_A3_BD, ADM0_A3_UA, ADM0_A3_UN, ADM0_A3_WB, CONTINENT, REGION_UN, SUBREGION, REGION_WB, NAME_LEN, LONG_LEN, ABBREV_LEN, TINY, ...]
Index: []

[0 rows x 169 columns]

In [39]:
df_clusters.to_parquet('../data/clusters/clusters_kmean_random.parquet')

In [40]:
def find_countries_missing_from_clusters(df_hpi, df_clusters, country_column='Country'):
    """
    Identifies which countries are present in the HPI DataFrame but missing from the cluster DataFrame.

    Parameters:
    - df_hpi: DataFrame where columns are country names and rows are years (House Price Index data)
    - df_clusters: DataFrame with country names and cluster assignments
    - country_column: Name of the column in df_clusters that contains country names (default: 'Country')

    Returns:
    - List of country names that are in df_hpi but not in df_clusters
    """

    # Extract country names from HPI DataFrame (column headers)
    hpi_countries = set(df_hpi.columns)

    # Extract country names from cluster DataFrame
    cluster_countries = set(df_clusters[country_column].unique())

    # Find countries present in HPI but missing from clusters
    missing_countries = hpi_countries - cluster_countries

    # Print results
    if missing_countries:
        print("Countries in HPI that are missing from the cluster DataFrame:")
        for country in sorted(missing_countries):
            print(f" - {country}")
    else:
        print("All countries in the HPI DataFrame are present in the cluster DataFrame.")

    return list(missing_countries)

In [41]:
find_countries_missing_from_clusters(df_countries_hpi, df_clusters)

Countries in HPI that are missing from the cluster DataFrame:
 - China
 - Czech-Republic
 - Hong-Kong
 - Indonesia
 - Macedonia
 - Morocco
 - New-Zealand
 - South-Africa
 - South-Korea
 - United-Kingdom
 - Year

['Morocco',
 'Czech-Republic',
 'Year',
 'China',
 'South-Korea',
 'South-Africa',
 'Hong-Kong',
 'United-Kingdom',
 'Indonesia',
 'Macedonia',
 'New-Zealand']

In [42]:
def find_countries_missing_from_clusters(df_hpi, df_clusters, country_column='Country'):
    """
    Identifies which countries are present in the HPI DataFrame but missing from the cluster DataFrame.
    Handles country name formatting differences (e.g., '-' vs ' ') and ignores the year column.

    Parameters:
    - df_hpi: DataFrame where columns are country names and rows are years (House Price Index data)
    - df_clusters: DataFrame with country names and cluster assignments
    - country_column: Name of the column in df_clusters that contains country names (default: 'Country')

    Returns:
    - List of country names that are in df_hpi but not in df_clusters
    """

    # Step 1: Remove the year column (assumed to be the first column)
    hpi_country_columns = df_hpi.columns[1:]

    # Step 2: Normalize country names by replacing '-' with ' '
    hpi_countries = set(col.replace('-', ' ').strip() for col in hpi_country_columns)

    # Step 3: Normalize cluster country names
    cluster_countries = set(df_clusters[country_column].str.strip())

    # Step 4: Find missing countries
    missing_countries = hpi_countries - cluster_countries

    # Step 5: Print results
    if missing_countries:
        print("Countries in HPI that are missing from the cluster DataFrame:")
        for country in sorted(missing_countries):
            print(f" - {country}")
    else:
        print("All countries in the HPI DataFrame are present in the cluster DataFrame.")

    return list(missing_countries)

In [44]:
countries_delete = find_countries_missing_from_clusters(df_countries_hpi, df_clusters)

Countries in HPI that are missing from the cluster DataFrame:
 - China
 - Czech Republic
 - Hong Kong
 - Indonesia
 - Macedonia
 - Morocco

In [45]:
# Supongamos que ya tenés la lista de países faltantes con espacios
# Ejemplo: missing_countries = ['United States', 'South Korea']

# Convertir los nombres con espacios a formato con guiones
columns_to_drop = [country.replace(' ', '-') for country in countries_delete]

# Eliminar esas columnas del DataFrame HPI
df_countries_hpi = df_countries_hpi.drop(columns=columns_to_drop)

In [49]:
df_countries_hpi.shape

(15, 52)

In [50]:
df_clusters.shape

(53, 4)

- dos de mas ya que en df_countries_hpi tenemos columna 'Year' y en df_cluster tenemos valor de 'Paraguay'

In [53]:
print(list(df_countries_hpi.columns))

['Year', 'Australia', 'Austria', 'Belgium', 'Brazil', 'Bulgaria', 'Canada', 'Chile', 'Colombia', 'Croatia', 'Cyprus', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'India', 'Ireland', 'Israel', 'Italy', 'Japan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malaysia', 'Malta', 'Mexico', 'Netherlands', 'New-Zealand', 'Norway', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia', 'South-Africa', 'South-Korea', 'Spain', 'Sweden', 'Switzerland', 'Thailand', 'Turkey', 'USA', 'United-Kingdom']

In [55]:
print(list(df_clusters.Country))

['Australia', 'Austria', 'Belgium', 'Brazil', 'Bulgaria', 'Canada', 'Chile', 'Colombia', 'Croatia', 'Cyprus', 'Czech', 'Denmark', 'Estonia', 'Finland', 'France', 'Germany', 'Greece', 'Hungary', 'Iceland', 'India', 'Ireland', 'Israel', 'Italy', 'Japan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malaysia', 'Malta', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia', 'Serbia', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa', 'South Korea', 'Spain', 'Sweden', 'Switzerland', 'Thailand', 'Turkey', 'United Kingdom', 'USA']

In [56]:
# Reemplazar 'Czech' por 'Czech Republic' en la columna 'Country'
df_clusters['Country'] = df_clusters['Country'].replace({'Czech': 'Czech Republic'})

In [57]:
df_clusters

           Country iso_a3  cluster      CONTINENT
0        Australia    AUS        1        Oceania
1          Austria    AUT        0         Europe
2          Belgium    BEL        0         Europe
3           Brazil    BRA        1  South America
4         Bulgaria    BGR        0         Europe
5           Canada    CAN        1  North America
6            Chile    CHL        2  South America
7         Colombia    COL        2  South America
8          Croatia    HRV        0         Europe
9           Cyprus    CYP        0           Asia
10  Czech Republic    CZE        1         Europe
11         Denmark    DNK        1         Europe
12         Estonia    EST        0         Europe
13         Finland    FIN        0         Europe
14          France    FRA        1         Europe
15         Germany    DEU        1         Europe
16          Greece    GRC        0         Europe
17         Hungary    HUN        1         Europe
18         Iceland    ISL        1         Europe
19           India    IND        2           Asia
20         Ireland    IRL        0         Europe
21          Israel    ISR        1           Asia
22           Italy    ITA        1         Europe
23           Japan    JPN        2           Asia
24          Latvia    LVA        0         Europe
25       Lithuania    LTU        0         Europe
26      Luxembourg    LUX        0         Europe
27        Malaysia    MYS        1           Asia
28           Malta    MLT        0         Europe
29          Mexico    MEX        1  North America
30     Netherlands    NLD        1         Europe
31     New Zealand    NZL        0        Oceania
32          Norway    NOR        1         Europe
33        Paraguay    PRY        2  South America
34            Peru    PER        1  South America
35     Philippines    PHL        1           Asia
36          Poland    POL        1         Europe
37        Portugal    PRT        0         Europe
38         Romania    ROU        1         Europe
39          Russia    RUS        2         Europe
40          Serbia    SRB        1         Europe
41       Singapore    SGP        1           Asia
42        Slovakia    SVK        0         Europe
43        Slovenia    SVN        0         Europe
44    South Africa    ZAF        1         Africa
45     South Korea    KOR        2           Asia
46           Spain    ESP        1         Europe
47          Sweden    SWE        1         Europe
48     Switzerland    CHE        1         Europe
49        Thailand    THA        1           Asia
50          Turkey    TUR        1           Asia
51  United Kingdom    GBR        1         Europe
52             USA    USA        1  North America

In [59]:
countries_delete = find_countries_missing_from_clusters(df_countries_hpi, df_clusters)

Countries in HPI that are missing from the cluster DataFrame:
 - China
 - Hong Kong
 - Indonesia
 - Macedonia
 - Morocco

In [60]:
# Supongamos que ya tenés la lista de países faltantes con espacios
# Ejemplo: missing_countries = ['United States', 'South Korea']

# Convertir los nombres con espacios a formato con guiones
columns_to_drop = [country.replace(' ', '-') for country in countries_delete]

# Eliminar esas columnas del DataFrame HPI
df_countries_hpi = df_countries_hpi.drop(columns=columns_to_drop)

In [61]:
countries_delete = find_countries_missing_from_clusters(df_countries_hpi, df_clusters)

All countries in the HPI DataFrame are present in the cluster DataFrame.

In [62]:
df_countries_hpi.shape

(15, 53)

In [63]:
df_clusters.shape

(53, 4)

In [64]:
df_clusters.to_parquet('../data/clusters/clusters_kmean_random.parquet')
df_countries_hpi.to_parquet('../data/clusters/countries_hpi_for_clusters.parquet')

In [65]:
def standardize_country_names(df, column='Country'):
    """
    Replaces spaces with hyphens in country names within the specified column.

    Parameters:
    - df: DataFrame containing country names
    - column: Name of the column to standardize (default: 'Country')

    Returns:
    - DataFrame with standardized country names
    """
    df[column] = df[column].str.replace(' ', '-', regex=False).str.strip()
    return df

In [66]:
df_clusters = standardize_country_names(df_clusters)
df_clusters

           Country iso_a3  cluster      CONTINENT
0        Australia    AUS        1        Oceania
1          Austria    AUT        0         Europe
2          Belgium    BEL        0         Europe
3           Brazil    BRA        1  South America
4         Bulgaria    BGR        0         Europe
5           Canada    CAN        1  North America
6            Chile    CHL        2  South America
7         Colombia    COL        2  South America
8          Croatia    HRV        0         Europe
9           Cyprus    CYP        0           Asia
10  Czech-Republic    CZE        1         Europe
11         Denmark    DNK        1         Europe
12         Estonia    EST        0         Europe
13         Finland    FIN        0         Europe
14          France    FRA        1         Europe
15         Germany    DEU        1         Europe
16          Greece    GRC        0         Europe
17         Hungary    HUN        1         Europe
18         Iceland    ISL        1         Europe
19           India    IND        2           Asia
20         Ireland    IRL        0         Europe
21          Israel    ISR        1           Asia
22           Italy    ITA        1         Europe
23           Japan    JPN        2           Asia
24          Latvia    LVA        0         Europe
25       Lithuania    LTU        0         Europe
26      Luxembourg    LUX        0         Europe
27        Malaysia    MYS        1           Asia
28           Malta    MLT        0         Europe
29          Mexico    MEX        1  North America
30     Netherlands    NLD        1         Europe
31     New-Zealand    NZL        0        Oceania
32          Norway    NOR        1         Europe
33        Paraguay    PRY        2  South America
34            Peru    PER        1  South America
35     Philippines    PHL        1           Asia
36          Poland    POL        1         Europe
37        Portugal    PRT        0         Europe
38         Romania    ROU        1         Europe
39          Russia    RUS        2         Europe
40          Serbia    SRB        1         Europe
41       Singapore    SGP        1           Asia
42        Slovakia    SVK        0         Europe
43        Slovenia    SVN        0         Europe
44    South-Africa    ZAF        1         Africa
45     South-Korea    KOR        2           Asia
46           Spain    ESP        1         Europe
47          Sweden    SWE        1         Europe
48     Switzerland    CHE        1         Europe
49        Thailand    THA        1           Asia
50          Turkey    TUR        1           Asia
51  United-Kingdom    GBR        1         Europe
52             USA    USA        1  North America

In [67]:
df_clusters.to_parquet('../data/clusters/clusters_kmean_random.parquet')

In [68]:
def print_cluster_groups(df_clusters):
    """
    Groups countries by their cluster and prints each group with country name and continent.

    Parameters:
    - df_clusters: DataFrame containing 'Country', 'cluster', and 'CONTINENT' columns
    """

    # Ensure required columns exist
    required_cols = {'Country', 'cluster', 'CONTINENT'}
    if not required_cols.issubset(df_clusters.columns):
        print("Missing required columns in the DataFrame.")
        return

    # Group countries by cluster
    grouped = df_clusters.groupby('cluster')

    # Print each cluster group
    for cluster_id, group in grouped:
        print(f"\n🌍 Cluster {cluster_id} ({len(group)} countries):")
        for _, row in group.iterrows():
            country = row['Country']
            continent = row['CONTINENT']
            print(f" - {country} ({continent})")

In [69]:
print_cluster_groups(df_clusters)

🌍 Cluster 0 (17 countries):
 - Austria (Europe)
 - Belgium (Europe)
 - Bulgaria (Europe)
 - Croatia (Europe)
 - Cyprus (Asia)
 - Estonia (Europe)
 - Finland (Europe)
 - Greece (Europe)
 - Ireland (Europe)
 - Latvia (Europe)
 - Lithuania (Europe)
 - Luxembourg (Europe)
 - Malta (Europe)
 - New-Zealand (Oceania)
 - Portugal (Europe)
 - Slovakia (Europe)
 - Slovenia (Europe)

🌍 Cluster 1 (29 countries):
 - Australia (Oceania)
 - Brazil (South America)
 - Canada (North America)
 - Czech-Republic (Europe)
 - Denmark (Europe)
 - France (Europe)
 - Germany (Europe)
 - Hungary (Europe)
 - Iceland (Europe)
 - Israel (Asia)
 - Italy (Europe)
 - Malaysia (Asia)
 - Mexico (North America)
 - Netherlands (Europe)
 - Norway (Europe)
 - Peru (South America)
 - Philippines (Asia)
 - Poland (Europe)
 - Romania (Europe)
 - Serbia (Europe)
 - Singapore (Asia)
 - South-Africa (Africa)
 - Spain (Europe)
 - Sweden (Europe)
 - Switzerland (Europe)
 - Thailand (Asia)
 - Turkey (Asia)
 - United-Kingdom (Europe)
 - USA (North America)

🌍 Cluster 2 (7 countries):
 - Chile (South America)
 - Colombia (South America)
 - India (Asia)
 - Japan (Asia)
 - Paraguay (South America)
 - Russia (Europe)
 - South-Korea (Asia)