In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import time
import os
import numpy as np

In [2]:
aus_df = pd.read_parquet('../data/by_country/Australia_macro_profile.parquet')

In [3]:
aus_df

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price,rule_of_law_df,share_of_industry_df,tax_revenue_df,inflation_df,edu_spending_df,govermment_effective_df
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,78.7775,NaN,283.4875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,87.3575,NaN,309.1825,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,86.2500,NaN,315.9400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,89.9575,NaN,341.5600,NaN,NaN,100.0000,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,97.0800,NaN,367.2525,NaN,NaN,97.8450,NaN,NaN,NaN,NaN,NaN,NaN
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,106.9800,101.025,378.9825,NaN,NaN,97.5325,NaN,NaN,NaN,NaN,NaN,NaN
6,2013,NaN,NaN,NaN,NaN,NaN,52.751667,106.8425,103.500,392.4275,NaN,NaN,103.9925,NaN,NaN,NaN,NaN,NaN,NaN
7,2014,NaN,NaN,NaN,NaN,NaN,60.172500,106.6775,106.075,403.4525,2059.295833,NaN,113.4075,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,NaN,102.4,45.31,NaN,80.1975,62.596667,105.8950,107.675,409.8350,2207.458333,NaN,123.6450,NaN,NaN,21.87,NaN,5.46,NaN
9,2016,12.73,96.8,44.54,85.80,85.2900,60.568333,104.4575,109.050,424.6600,2367.798333,5.713333,130.4450,1.72,NaN,22.26,NaN,5.43,1.53
10,2017,13.01,91.0,48.34,85.90,89.7925,73.416667,109.4400,111.175,450.3775,2493.594167,5.606667,141.3350,1.65,23.47,22.09,1.9,5.32,1.50
11,2018,13.31,97.2,46.66,86.01,95.3525,71.986667,114.2550,113.300,473.9000,2550.039167,5.306667,139.3050,1.67,24.12,23.18,1.9,5.41,1.56
12,2019,13.59,97.7,47.12,86.12,103.7050,73.037500,113.9775,115.125,498.6975,2589.645000,5.165000,133.6400,1.69,25.27,23.38,1.6,5.51,1.54
13,2020,13.58,90.6,46.25,86.24,113.1950,65.861667,111.7475,116.100,494.0275,2656.729167,6.441667,140.8525,1.62,25.39,22.56,0.8,5.38,1.57
14,2021,13.80,87.9,47.26,86.36,122.0550,68.871667,127.3975,119.425,550.6875,2760.232500,5.138333,165.3925,1.64,25.42,23.03,2.9,5.33,1.47
15,2022,14.07,87.5,47.26,86.49,133.1300,81.175833,142.0275,127.300,620.9125,2991.540000,3.725833,179.0200,1.51,27.48,23.60,6.6,5.21,1.53
16,2023,14.50,NaN,NaN,86.62,142.2425,90.190000,157.1425,134.425,655.5775,3173.511667,3.686667,178.6500,1.52,27.65,NaN,5.6,NaN,1.59
17,2024,NaN,NaN,NaN,NaN,154.9175,94.169167,166.4175,138.675,680.3275,3340.351667,3.686667,192.5275,NaN,25.97,NaN,3.2,NaN,NaN

In [6]:
aus_df.shape

(18, 19)

In [7]:
aut_df = pd.read_parquet('../data/by_country/Austria_macro_profile.parquet')

In [8]:
aut_df

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price,rule_of_law_df,share_of_industry_df,tax_revenue_df,inflation_df,edu_spending_df,govermment_effective_df
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,16.3250,NaN,70.5500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,17.1725,NaN,72.9600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,16.2225,NaN,71.5675,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,16.0700,NaN,73.5125,NaN,NaN,100.0000,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,17.4950,NaN,77.0425,NaN,NaN,104.2250,NaN,NaN,NaN,NaN,NaN,NaN
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,18.1675,95.745833,79.1475,NaN,NaN,117.1325,NaN,NaN,NaN,NaN,NaN,NaN
6,2013,NaN,NaN,NaN,NaN,NaN,18.548333,18.7175,97.773333,80.2975,NaN,NaN,122.5900,NaN,NaN,NaN,NaN,NaN,NaN
7,2014,NaN,NaN,NaN,NaN,NaN,19.199167,18.9550,99.201667,82.5275,273.5900,NaN,126.7900,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,NaN,101.2,32.94,NaN,17.2125,21.557500,19.5825,100.000000,85.5200,274.8325,NaN,132.0575,NaN,NaN,26.83,NaN,5.46,NaN
9,2016,4.57,101.4,32.36,57.90,17.7625,22.639167,20.7375,100.970833,88.9175,280.1000,6.450000,141.7575,1.76,NaN,25.42,NaN,5.48,1.47
10,2017,4.60,101.4,32.17,58.09,18.1725,19.765833,21.8975,103.223333,91.8250,286.6575,5.925000,147.0825,1.80,25.80,25.42,2.1,5.37,1.47
11,2018,4.64,101.5,32.15,58.30,18.8050,20.140000,23.2950,105.411667,95.8075,298.1300,5.208333,157.2350,1.85,25.72,25.42,2.0,5.23,1.46
12,2019,4.66,101.1,32.13,58.51,19.5075,21.502500,24.8100,106.983333,98.9250,315.7025,4.841667,163.4250,1.86,25.54,25.58,1.5,5.22,1.49
13,2020,4.64,100.9,31.54,58.75,20.2600,24.295000,23.8975,108.468333,95.0800,330.5200,6.025000,174.9175,1.77,25.65,24.43,1.4,5.57,1.61
14,2021,4.69,100.3,31.54,58.99,22.1550,26.110000,26.2775,111.460833,101.5575,348.0075,6.200000,195.4825,1.75,25.73,25.85,2.8,5.49,1.53
15,2022,4.76,100.4,31.48,59.26,23.0850,31.935833,28.5300,121.066667,112.0025,375.0325,4.758333,215.6150,1.70,25.21,26.24,8.5,4.77,1.46
16,2023,4.83,NaN,NaN,59.53,24.5500,29.365000,29.4575,130.399167,118.3075,381.3100,5.108333,212.0800,1.75,25.24,NaN,7.8,NaN,1.33
17,2024,NaN,NaN,NaN,NaN,26.6925,31.460833,29.7075,134.206667,121.0575,379.1125,5.108333,207.6200,NaN,23.06,NaN,2.9,NaN,NaN

In [9]:
aut_df.shape

(18, 19)

In [10]:
py_df = pd.read_parquet('../data/by_country/Paraguay_macro_profile.parquet')

In [11]:
py_df.shape

(18, 19)

In [12]:
py_df

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price,rule_of_law_df,share_of_industry_df,tax_revenue_df,inflation_df,edu_spending_df,govermment_effective_df
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,4017.8350,NaN,22466.5125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,5082.0850,NaN,26850.8950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,5144.1425,NaN,27757.7350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,6871.4875,NaN,32273.2200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,7409.5675,NaN,35371.6125,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,7190.5000,81.678483,36806.3775,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,2013,NaN,NaN,NaN,NaN,NaN,5.810833,7925.3875,83.870625,41587.7025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,2014,NaN,NaN,NaN,NaN,NaN,6.500833,8908.4650,88.088325,45043.5150,54563.191667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,NaN,96.7,40.68,NaN,5561.5775,6.701667,9141.0500,90.844608,47119.3325,67513.942500,NaN,NaN,NaN,NaN,9.64,NaN,NaN,NaN
9,2016,3.07,101.6,40.83,61.03,5813.5125,6.731667,9761.4800,94.557258,51161.8200,71808.759167,6.0850,NaN,-0.69,NaN,9.56,NaN,3.43,-0.82
10,2017,3.13,113.0,40.97,61.30,6084.8525,7.841667,10513.6200,97.963675,54780.5700,73508.770000,6.0850,NaN,-0.67,34.39,9.96,3.6,3.09,-0.84
11,2018,3.26,106.9,41.12,61.58,6640.7400,8.271667,11499.3225,101.858333,57644.1200,82234.815000,6.2375,NaN,-0.60,33.56,10.08,4.0,3.30,-0.60
12,2019,3.33,105.3,41.28,61.88,7068.6525,7.959167,11070.3450,104.666667,59170.3725,93416.321667,6.5700,NaN,-0.57,33.49,10.00,2.8,3.49,-0.58
13,2020,3.28,112.0,41.42,62.18,7583.9875,8.899167,11925.2225,106.516667,59978.6850,101165.776667,7.7100,NaN,-0.43,34.20,9.52,1.8,3.94,-0.57
14,2021,3.41,113.4,41.57,62.50,8128.2400,9.987500,15517.3325,111.616667,67658.4725,112769.130000,7.5075,NaN,-0.58,34.68,9.79,4.8,3.41,-0.66
15,2022,3.39,113.4,41.99,62.82,8685.2325,9.538333,16199.7500,122.516667,73236.6950,127254.085000,6.7275,NaN,-0.59,34.25,10.27,9.8,3.40,-0.61
16,2023,3.46,NaN,NaN,63.15,9528.0425,9.898333,16218.5525,128.191667,78570.4900,139338.302500,5.8850,NaN,-0.58,32.90,NaN,4.6,3.41,-0.46
17,2024,NaN,NaN,NaN,NaN,10601.3175,10.151667,17618.0475,133.108333,84028.5975,160700.547500,5.8050,NaN,NaN,32.49,NaN,3.8,NaN,NaN

In [14]:
from scipy.stats import skew, kurtosis
from sklearn.linear_model import LinearRegression

In [21]:
def build_master_dataframe(directory_path):
    start_time = time.time()
    master_rows = []

    # Recorremos todos los archivos parquet en el directorio
    for filename in os.listdir(directory_path):
        if filename.endswith(".parquet"):
            file_path = os.path.join(directory_path, filename)
            df = pd.read_parquet(file_path)

            # Extraemos el nombre del país del nombre del archivo
            country_name = filename.split("_")[0]

            # Filtramos desde el año 2015 en adelante
            df = df[df["Year"] >= 2015].copy()

            # Rellenamos datos faltantes
            df = df.ffill().bfill()

            # Inicializamos diccionario para almacenar los features del país
            country_features = {"Country": country_name}

            # Iteramos sobre cada macroeconómico (todas las columnas excepto "Year")
            macro_columns = [col for col in df.columns if col != "Year"]

            for col in macro_columns:
                series = df[col].values
                years = df["Year"].values.reshape(-1, 1)

                # Calculamos estadísticos
                country_features[f"{col}_mean"] = np.mean(series)
                country_features[f"{col}_median"] = np.median(series)
                country_features[f"{col}_std"] = np.std(series)
                country_features[f"{col}_cv"] = np.std(series) / np.mean(series) if np.mean(series) != 0 else 0
                country_features[f"{col}_min"] = np.min(series)
                country_features[f"{col}_max"] = np.max(series)
                country_features[f"{col}_skew"] = skew(series)
                country_features[f"{col}_kurtosis"] = kurtosis(series)
                country_features[f"{col}_last"] = series[-1]
                country_features[f"{col}_growth"] = (series[-1] - series[0]) / series[0] if series[0] != 0 else 0

                # Pendiente de regresión lineal (tendencia)
                try:
                    model = LinearRegression().fit(years, series)
                    country_features[f"{col}_trend"] = model.coef_[0]
                except:
                    country_features[f"{col}_trend"] = np.nan

            # Agregamos el vector de features al master
            master_rows.append(country_features)

    # Convertimos a DataFrame final
    master_df = pd.DataFrame(master_rows)
    end_time = time.time()
    print(f"Time taken to perform feature engineering:{round(end_time- start_time, 2)} seg.")
    return master_df

In [16]:
one_point_au = build_master_dataframe('../data/example_feature_engineering/')

Time taken to perform feature engineering:0.07

In [17]:
one_point_au

,Country,labor_force_mean,labor_force_median,labor_force_std,labor_force_cv,labor_force_min,labor_force_max,labor_force_skew,labor_force_kurtosis,labor_force_last,...,govermment_effective_df_median,govermment_effective_df_std,govermment_effective_df_cv,govermment_effective_df_min,govermment_effective_df_max,govermment_effective_df_skew,govermment_effective_df_kurtosis,govermment_effective_df_last,govermment_effective_df_growth,govermment_effective_df_trend
0,Australia,13.582,13.585,0.618398,0.045531,12.73,14.5,0.09709,-1.190852,14.5,...,1.535,0.03618,0.023478,1.47,1.59,-0.346877,-0.62772,1.59,0.039216,0.005273

In [22]:
one_point_country_df = build_master_dataframe("../data/by_country/")

C:\Users\lucas\AppData\Local\Temp\ipykernel_37336\1458993150.py:37: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  country_features[f"{col}_skew"] = skew(series)
C:\Users\lucas\AppData\Local\Temp\ipykernel_37336\1458993150.py:38: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  country_features[f"{col}_kurtosis"] = kurtosis(series)
C:\Users\lucas\AppData\Local\Temp\ipykernel_37336\1458993150.py:37: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  country_features[f"{col}_skew"] = skew(series)
C:\Users\lucas\AppData\Local\Temp\ipykernel_37336\1458993150.py:38: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  country_features[f"{col}_kurtosis"] = kurtosis(series)
C:\Users\lucas\AppData\Local\Temp\ipykernel_37336\1458993150.py:37: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  country_features[f"{col}_skew"] = skew(series)
C:\Users\lucas\AppData\Local\Temp\ipykernel_37336\1458993150.py:38: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  country_features[f"{col}_kurtosis"] = kurtosis(series)
C:\Users\lucas\AppData\Local\Temp\ipykernel_37336\1458993150.py:37: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  country_features[f"{col}_skew"] = skew(series)
C:\Users\lucas\AppData\Local\Temp\ipykernel_37336\1458993150.py:38: RuntimeWarning: Precision loss occurred in moment calculation due to catastrophic cancellation. This occurs when the data are nearly identical. Results may be unreliable.
  country_features[f"{col}_kurtosis"] = kurtosis(series)

Time taken to perform feature engineering:2.12 seg.

In [24]:
def build_master_dataframe(directory_path):
    start_time = time.time()
    master_rows = []

    for filename in os.listdir(directory_path):
        if filename.endswith(".parquet"):
            file_path = os.path.join(directory_path, filename)
            df = pd.read_parquet(file_path)

            country_name = filename.split("_")[0]
            df = df[df["Year"] >= 2015].copy()
            df = df.ffill().bfill()

            country_features = {"Country": country_name}
            macro_columns = [col for col in df.columns if col != "Year"]

            for col in macro_columns:
                series = df[col].values
                years = df["Year"].values.reshape(-1, 1)

                # Estadísticos básicos
                country_features[f"{col}_mean"] = np.mean(series)
                country_features[f"{col}_median"] = np.median(series)
                country_features[f"{col}_std"] = np.std(series)
                country_features[f"{col}_cv"] = np.std(series) / np.mean(series) if np.mean(series) != 0 else 0
                country_features[f"{col}_min"] = np.min(series)
                country_features[f"{col}_max"] = np.max(series)
                country_features[f"{col}_last"] = series[-1]
                country_features[f"{col}_growth"] = (series[-1] - series[0]) / series[0] if series[0] != 0 else 0

                # Skewness y kurtosis con control de precisión
                if np.std(series) < 1e-8:
                    country_features[f"{col}_skew"] = 0
                    country_features[f"{col}_kurtosis"] = 0
                else:
                    country_features[f"{col}_skew"] = skew(series)
                    country_features[f"{col}_kurtosis"] = kurtosis(series)

                # Pendiente de regresión lineal
                try:
                    model = LinearRegression().fit(years, series)
                    country_features[f"{col}_trend"] = model.coef_[0]
                except:
                    country_features[f"{col}_trend"] = np.nan

            master_rows.append(country_features)

    master_df = pd.DataFrame(master_rows)
    end_time = time.time()
    print(f"Time taken to perform feature engineering:{round(end_time- start_time, 2)} seg.")
    return master_df

In [25]:
one_point_country_df = build_master_dataframe("../data/by_country/")

Time taken to perform feature engineering:1.65 seg.

In [26]:
one_point_country_df.head()

,Country,labor_force_mean,labor_force_median,labor_force_std,labor_force_cv,labor_force_min,labor_force_max,labor_force_last,labor_force_growth,labor_force_skew,...,govermment_effective_df_median,govermment_effective_df_std,govermment_effective_df_cv,govermment_effective_df_min,govermment_effective_df_max,govermment_effective_df_last,govermment_effective_df_growth,govermment_effective_df_skew,govermment_effective_df_kurtosis,govermment_effective_df_trend
0,Australia,13.582,13.585,0.618398,0.045531,12.73,14.50,14.50,0.139042,0.097090,...,1.535,0.036180,2.347833e-02,1.47,1.59,1.59,0.039216,-0.346877,-0.627720,0.005273
1,Austria,4.679,4.650,0.092569,0.019784,4.57,4.83,4.83,0.056893,0.530756,...,1.470,0.078968,5.401392e-02,1.33,1.61,1.33,-0.095238,-0.207178,-0.148237,-0.011879
2,Belgium,5.205,5.180,0.151013,0.029013,5.00,5.42,5.42,0.084000,0.146086,...,1.165,0.129016,1.088738e-01,1.04,1.40,1.04,-0.257143,0.542175,-1.048411,-0.037758
3,Brazil,103.729,103.950,2.291325,0.022090,99.69,106.30,106.10,0.048419,-0.373023,...,-0.480,0.135632,-3.214025e-01,-0.59,-0.23,-0.55,1.200000,0.321185,-1.620024,-0.038182
4,Bulgaria,3.255,3.270,0.095525,0.029347,3.09,3.38,3.09,-0.055046,-0.624667,...,0.070,0.146969,-5.295130e+16,-0.27,0.17,0.05,-0.444444,-0.794950,-1.012397,-0.022303

In [27]:
one_point_country_df.tail()

,Country,labor_force_mean,labor_force_median,labor_force_std,labor_force_cv,labor_force_min,labor_force_max,labor_force_last,labor_force_growth,labor_force_skew,...,govermment_effective_df_median,govermment_effective_df_std,govermment_effective_df_cv,govermment_effective_df_min,govermment_effective_df_max,govermment_effective_df_last,govermment_effective_df_growth,govermment_effective_df_skew,govermment_effective_df_kurtosis,govermment_effective_df_trend
55,Thailand,40.257,40.22,0.465039,0.011552,39.71,40.97,40.82,0.027953,0.205878,...,0.225,0.041425,0.195399,0.13,0.26,0.17,-0.260870,-0.581054,-0.813927,-0.010667
56,Turkey,33.394,33.38,1.529223,0.045793,31.49,35.59,35.59,0.130200,0.202010,...,-0.095,0.093643,-0.843630,-0.25,-0.01,-0.25,24.000000,-0.311503,-1.487279,-0.029879
57,United-Kingdom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.345,0.125275,0.092968,1.16,1.57,1.16,-0.261146,0.227219,-0.913696,-0.051190
58,United,34.473,34.46,0.453785,0.013163,33.88,35.19,35.19,0.038666,0.280498,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,USA,166.460,166.15,2.732471,0.016415,162.70,170.70,170.70,0.049170,0.200181,...,1.370,0.118085,0.086446,1.22,1.54,1.22,-0.152778,0.105426,-1.597092,-0.034667

In [30]:
uk_df = pd.read_parquet('../data/by_country/United-Kingdom_data.parquet')

In [32]:
uk_df_2 = pd.read_parquet('../data/by_country/United_Kingdom_macro_profile.parquet')

In [31]:
uk_df

   Year  govermment_effective_df
0  2016                     1.57
1  2017                     1.43
2  2018                     1.36
3  2019                     1.45
4  2020                     1.33
5  2021                     1.24
6  2022                     1.24
7  2023                     1.16

In [33]:
uk_df_2

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,70.0750,NaN,386.1575,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,70.3125,NaN,398.4000,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,62.5150,NaN,387.2025,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,64.5750,NaN,402.1400,NaN,NaN,100.0000
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,65.3075,NaN,415.6475,NaN,NaN,98.5450
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,67.5025,96.041667,428.4300,NaN,NaN,98.9200
6,2013,NaN,NaN,NaN,NaN,NaN,129.022500,71.1100,98.508333,445.3400,NaN,NaN,101.4550
7,2014,NaN,NaN,NaN,NaN,NaN,134.969167,77.1675,99.958333,465.6300,1594.228333,NaN,109.6025
8,2015,NaN,100.5,70.84,NaN,93.6600,149.983333,83.2450,100.008333,479.1125,1618.274167,NaN,116.1250
9,2016,33.88,100.9,71.71,82.89,95.6900,166.655833,89.1525,100.650000,497.9125,1684.606667,4.891667,124.2700
10,2017,34.07,102.5,72.20,83.14,97.1425,175.003333,95.0025,103.358333,520.6200,1734.642500,4.383333,129.9250
11,2018,34.36,104.3,71.72,83.40,99.7675,188.556667,96.8300,105.916667,538.0775,1811.995000,4.075000,134.0400
12,2019,34.63,106.0,72.42,83.65,106.6500,194.944167,101.6075,107.800000,558.4825,1873.763333,3.850000,135.3700
13,2020,34.56,106.8,71.34,83.90,118.9150,208.609167,92.0850,108.783333,525.8700,1936.857500,4.600000,139.2375
14,2021,34.24,106.5,71.16,84.15,127.1775,218.990833,101.2350,111.608333,571.3500,1985.519167,4.541667,150.5825
15,2022,34.73,105.2,69.57,84.40,131.5625,212.458333,112.7750,120.450000,631.6075,2058.680000,3.783333,164.5475
16,2023,35.19,NaN,NaN,84.64,140.6150,208.479167,119.5125,128.633333,677.7950,2088.522500,4.066667,165.0025
17,2024,NaN,NaN,NaN,NaN,149.6275,217.076667,124.0375,132.841667,712.7475,2098.692500,4.066667,166.3750

In [34]:
one_point_country_df[one_point_country_df.isna().any(axis=1)]["Country"]

10    Czech-Republic
11             Czech
18         Hong-Kong
19              Hong
21           Iceland
24            Israel
31             Malta
34       New-Zealand
35               New
37          Paraguay
48      South-Africa
49       South-Korea
50             South
51             South
57    United-Kingdom
58            United
Name: Country, dtype: object

In [56]:
czech_df_01 = pd.read_parquet('../data/by_country/Czech_Republic_macro_profile.parquet')
czech_df_02 = pd.read_parquet('../data/by_country/Czech-Republic_data.parquet')
hongkong_df_01 = pd.read_parquet('../data/by_country/Hong_Kong_macro_profile.parquet')
hongkong_df_02 = pd.read_parquet('../data/by_country/Hong-Kong_data.parquet')
iceland_df_01 = pd.read_parquet('../data/by_country/Iceland_macro_profile.parquet')
israel_df_01 = pd.read_parquet('../data/by_country/Israel_macro_profile.parquet')
malta_df_01 = pd.read_parquet('../data/by_country/Malta_macro_profile.parquet')
new_zealand_df_01 = pd.read_parquet('../data/by_country/New_Zealand_macro_profile.parquet')
new_zealand_df_02 = pd.read_parquet('../data/by_country/New-Zealand_data.parquet')
south_a_df_01 = pd.read_parquet('../data/by_country/South_Africa_macro_profile.parquet')
south_a_df_02 = pd.read_parquet('../data/by_country/South-Africa_data.parquet')
south_k_df_01 = pd.read_parquet('../data/by_country/South_Korea_macro_profile.parquet')
south_k_df_02 = pd.read_parquet('../data/by_country/South-Korea_data.parquet')
uk_df_01 = pd.read_parquet('../data/by_country/United_Kingdom_macro_profile.parquet')
uk_df_02 = pd.read_parquet('../data/by_country/United-Kingdom_data.parquet')

In [47]:
iceland_df_01

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price,rule_of_law_df,share_of_industry_df,tax_revenue_df,inflation_df,edu_spending_df,govermment_effective_df
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,102.0250,NaN,351.6625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,100.8125,NaN,401.2175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,62.3425,NaN,408.3950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,59.1800,NaN,425.4825,NaN,NaN,100.0025,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,67.8100,NaN,446.2500,NaN,NaN,105.5050,NaN,NaN,NaN,NaN,NaN,NaN
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,73.7575,94.840833,467.3000,NaN,NaN,112.3750,NaN,NaN,NaN,NaN,NaN,NaN
6,2013,NaN,NaN,NaN,NaN,NaN,491.795000,76.6275,98.764167,496.1800,NaN,NaN,119.1850,NaN,NaN,NaN,NaN,NaN,NaN
7,2014,NaN,NaN,NaN,NaN,NaN,510.350833,89.6250,99.742500,526.9775,1992.150000,NaN,128.9450,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,NaN,100.3,18.67,NaN,139.2875,590.839167,111.6000,100.000833,583.7575,1985.070833,NaN,139.7425,NaN,NaN,22.69,NaN,7.46,NaN
9,2016,NaN,104.1,18.67,93.74,148.8525,753.122500,131.6200,100.790833,636.7875,2070.861667,3.341667,154.5925,1.48,NaN,37.61,NaN,7.43,1.35
10,2017,NaN,107.9,18.67,93.77,160.5025,714.010000,144.2325,99.125000,669.3500,2204.773333,3.283333,183.9925,1.57,19.20,23.92,1.8,7.58,1.41
11,2018,NaN,108.5,18.57,93.81,175.3350,694.605833,156.4350,99.858333,722.3000,2463.633333,3.100000,198.4925,1.68,19.82,22.98,2.7,7.56,1.43
12,2019,NaN,106.8,18.57,93.86,190.0000,798.462500,157.7525,101.853333,765.8550,2665.812500,3.925000,206.5100,1.73,19.85,21.93,3.0,7.60,1.48
13,2020,NaN,103.3,18.57,93.90,209.5500,917.633333,156.7075,103.058333,745.9925,2802.910000,6.433333,220.8375,1.75,20.73,22.40,2.8,8.58,1.48
14,2021,NaN,103.5,18.57,93.94,228.6000,882.272500,187.2875,106.840833,832.8850,3151.795000,6.016667,249.4875,1.71,21.05,21.41,4.4,8.22,1.59
15,2022,NaN,101.3,18.57,93.99,252.8350,879.947500,234.4025,112.959167,987.4575,3477.705833,3.591667,302.4725,1.70,21.87,22.52,8.3,7.14,1.56
16,2023,NaN,NaN,NaN,94.04,275.4025,790.423333,269.4750,121.964167,1092.9225,3770.335000,3.375000,322.8275,1.72,20.12,NaN,8.7,NaN,1.56
17,2024,NaN,NaN,NaN,NaN,298.1075,883.040000,305.2450,127.466667,1149.6000,4023.268333,3.375000,350.1350,NaN,19.40,NaN,5.9,NaN,NaN

In [48]:
israel_df_01

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price,rule_of_law_df,share_of_industry_df,tax_revenue_df,inflation_df,edu_spending_df,govermment_effective_df
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,37.0650,NaN,183.5725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,38.4950,NaN,193.7175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,38.0050,NaN,203.9400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,40.9925,NaN,218.4775,NaN,NaN,100.0000,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,47.9125,NaN,234.6300,NaN,NaN,110.5200,NaN,NaN,NaN,NaN,NaN,NaN
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,52.2350,86.033333,249.1100,NaN,NaN,114.0975,NaN,NaN,NaN,NaN,NaN,NaN
6,2013,NaN,NaN,NaN,NaN,NaN,78.843333,54.2850,87.341667,265.5425,NaN,NaN,124.4525,NaN,NaN,NaN,NaN,NaN,NaN
7,2014,NaN,NaN,NaN,NaN,NaN,86.024167,55.5400,87.758333,278.1350,754.374167,NaN,132.3600,NaN,NaN,NaN,NaN,NaN,NaN
8,2015,NaN,100.2,NaN,NaN,65.3075,87.510833,55.3350,87.216667,291.5900,792.600000,NaN,140.1150,NaN,NaN,23.07,NaN,5.80,NaN
9,2016,4.02,101.6,NaN,92.26,68.3175,95.970833,62.5950,86.750000,306.3075,834.832500,4.783333,150.5650,1.04,NaN,23.04,NaN,5.80,1.31
10,2017,4.09,104.5,NaN,92.34,71.6000,108.050000,64.8275,86.983333,319.7100,859.013333,4.225000,156.4350,0.99,18.56,24.24,0.3,6.01,1.35
11,2018,4.17,103.9,NaN,92.42,75.5675,115.756667,78.2400,87.666667,336.7500,902.115000,4.008333,155.1400,0.96,18.82,22.70,0.8,6.06,1.17
12,2019,4.23,103.4,NaN,92.50,79.0325,120.137500,81.5275,88.408333,356.1425,948.169167,3.816667,158.0650,1.01,18.92,22.11,0.8,6.04,1.29
13,2020,4.21,107.6,NaN,92.59,82.7200,151.702500,80.5050,87.858333,355.5975,987.480833,4.308333,162.9000,0.94,19.44,21.91,-0.6,6.48,1.05
14,2021,4.28,105.1,NaN,92.67,87.6275,198.805000,94.0525,89.191667,395.5800,1082.482500,5.050000,176.6475,0.91,18.84,24.62,1.5,6.18,1.25
15,2022,4.47,109.4,NaN,92.76,92.3250,197.190833,109.8650,93.108333,441.1000,1264.530000,3.766667,207.1650,0.94,19.43,25.01,4.4,6.46,1.24
16,2023,4.57,NaN,NaN,92.85,105.8425,200.111667,114.3925,97.041667,469.5925,1378.055833,3.466667,214.2300,0.78,18.50,NaN,4.2,NaN,1.15
17,2024,NaN,NaN,NaN,NaN,126.7375,212.894167,113.4075,100.008333,499.5200,1448.846667,3.466667,224.5400,NaN,17.35,NaN,3.1,NaN,NaN

In [49]:
malta_df_01

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price,rule_of_law_df,share_of_industry_df,tax_revenue_df,inflation_df,edu_spending_df,govermment_effective_df
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,0.3175,NaN,1.4450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,0.3150,NaN,1.5600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,0.3100,NaN,1.5725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,0.3575,NaN,1.7150,NaN,NaN,99.9975,NaN,NaN,NaN,NaN,NaN,NaN
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,0.3175,NaN,1.7550,NaN,NaN,98.6300,NaN,NaN,NaN,NaN,NaN,NaN
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,0.3700,97.132500,1.8700,NaN,NaN,101.6225,NaN,NaN,NaN,NaN,NaN,NaN
6,2013,NaN,NaN,NaN,NaN,NaN,0.450000,0.3525,98.083333,2.0325,NaN,NaN,101.2075,NaN,NaN,NaN,NaN,NaN,NaN
7,2014,NaN,NaN,NaN,NaN,NaN,0.598333,0.3775,98.840000,2.2375,8.180833,NaN,103.7875,NaN,NaN,NaN,NaN,7.00,NaN
8,2015,NaN,98.2,31.97,NaN,0.4325,0.532500,0.6050,100.002500,2.5550,8.381667,NaN,109.8325,NaN,NaN,24.30,NaN,5.02,NaN
9,2016,NaN,98.2,32.44,94.48,0.4600,0.625833,0.5775,100.902500,2.7175,8.423333,4.700000,115.8175,0.97,NaN,25.25,NaN,5.11,0.92
10,2017,NaN,96.0,32.44,94.55,0.4950,0.677500,0.5875,102.175000,3.1350,8.608333,4.008333,121.9375,1.11,11.52,25.06,1.4,4.56,0.97
11,2018,NaN,94.8,32.44,94.61,0.5475,0.774167,0.6550,103.954167,3.4200,9.090000,3.958333,129.0225,1.02,11.52,25.04,1.2,4.92,0.93
12,2019,NaN,86.5,32.44,94.68,0.6175,0.840833,0.7325,105.537500,3.6475,9.735833,4.083333,136.9025,0.92,12.07,24.46,1.6,4.90,0.82
13,2020,NaN,97.8,28.47,94.74,0.7075,0.772500,0.7450,106.368333,3.5925,10.327500,4.850000,141.5425,0.88,12.27,23.34,0.6,5.64,0.90
14,2021,NaN,95.6,27.34,94.81,0.7650,0.892500,0.9550,107.119167,4.1700,11.048333,3.766667,148.7375,0.84,12.02,23.82,1.5,5.36,0.85
15,2022,NaN,96.3,27.34,94.88,0.7925,1.121667,1.1075,113.685833,4.5650,11.829167,3.475000,158.6200,0.79,11.90,23.37,6.2,NaN,0.80
16,2023,NaN,NaN,NaN,94.94,0.8575,1.140000,0.9775,120.010833,5.1375,12.810000,3.483333,168.5050,0.70,11.81,NaN,5.1,NaN,0.40
17,2024,NaN,NaN,NaN,NaN,0.9600,1.320000,1.0325,122.940833,5.6150,13.795000,3.483333,179.3525,NaN,11.43,NaN,1.7,NaN,NaN

In [57]:
czech_df_01

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,286.0300,NaN,964.1600,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,291.7725,NaN,1009.3900,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,268.1400,NaN,986.3775,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,267.4050,NaN,1008.2400,NaN,NaN,99.9975
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,267.2050,NaN,1023.8400,NaN,NaN,100.0250
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,261.2600,97.975000,1029.5975,NaN,NaN,98.5550
6,2013,NaN,NaN,NaN,NaN,NaN,920.626667,258.2225,99.341667,1042.2525,NaN,NaN,98.5800
7,2014,NaN,NaN,NaN,NaN,NaN,1182.200000,270.7900,99.750000,1094.4975,2072.538333,NaN,100.9950
8,2015,NaN,101.3,45.25,NaN,220.0425,1431.200833,298.6050,100.008333,1162.9525,2202.911667,NaN,105.0125
9,2016,5.35,101.8,45.18,73.57,228.7500,1902.431667,294.3300,100.658333,1210.7600,2356.845833,3.966667,112.5225
10,2017,5.38,101.1,45.60,73.68,241.2400,3155.678333,307.2300,103.100000,1294.8350,2515.148333,2.908333,125.7025
11,2018,5.42,99.9,45.63,73.79,263.5200,3167.734167,340.1225,105.116667,1368.9450,2677.040000,2.266667,136.5175
12,2019,5.42,100.4,45.64,73.92,285.1500,3326.169167,379.4200,107.833333,1472.2175,2827.115000,2.016667,149.0150
13,2020,5.37,102.0,45.65,74.06,312.3775,3559.564167,372.0725,111.366667,1457.0775,2968.566667,2.550000,161.5650
14,2021,5.28,104.1,45.73,74.21,329.6800,3660.680833,413.7425,115.050000,1576.9375,3124.307500,2.808333,193.4650
15,2022,5.37,102.3,45.75,74.38,345.3600,3594.871667,487.9875,132.100000,1762.4675,3359.020833,2.400000,226.1500
16,2023,5.50,NaN,NaN,74.55,375.2300,3109.789167,535.0450,147.925000,1914.9125,3519.667500,2.633333,222.3975
17,2024,NaN,NaN,NaN,NaN,402.5625,3457.355833,533.5375,151.891667,2014.2575,3723.751667,2.633333,233.4225

In [51]:
new_zealand_df_01

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,11.0325,NaN,45.8300,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,10.9850,NaN,45.7650,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,9.8975,NaN,46.4225,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,8.2050,NaN,48.7800,NaN,NaN,99.9975
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,9.2850,NaN,52.8100,NaN,NaN,100.7500
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,10.0200,952.691675,53.9900,NaN,NaN,105.2500
6,2013,NaN,NaN,NaN,NaN,NaN,21.706667,11.3175,963.499175,56.9175,NaN,NaN,114.5900
7,2014,NaN,NaN,NaN,NaN,NaN,21.696667,13.5550,975.326250,59.8825,536.010833,NaN,122.0325
8,2015,NaN,101.7,40.68,NaN,10.4975,24.615000,14.0075,978.181075,61.8875,536.010833,NaN,137.1775
9,2016,2.65,99.7,40.31,86.40,11.7650,25.075000,15.5125,984.502450,66.1525,522.752500,4.425000,156.6250
10,2017,2.75,98.7,40.42,86.47,12.7300,27.933333,16.4700,1002.723500,70.5400,402.053333,4.283333,166.8025
11,2018,2.80,101.7,39.87,86.54,13.5800,29.369167,17.4050,1018.750000,74.0850,423.423333,4.141667,172.7950
12,2019,2.84,101.6,39.29,86.61,14.8100,28.171667,18.8950,1035.250000,79.2925,447.100833,4.100000,178.1925
13,2020,2.90,102.4,38.56,86.70,16.3375,27.615833,17.7750,1053.000000,80.8525,464.787500,4.250000,196.3125
14,2021,2.94,102.5,38.64,86.79,18.3650,20.604167,21.3350,1094.500000,87.9150,490.727500,3.975000,248.2650
15,2022,2.97,99.0,37.02,86.80,20.2750,20.954167,24.2725,1173.000000,95.2425,518.996667,3.808333,249.6925
16,2023,3.07,NaN,NaN,86.90,21.8525,26.227500,25.6875,1240.250000,102.6375,534.376667,3.966667,233.5425
17,2024,NaN,NaN,NaN,NaN,22.9875,33.073333,25.1525,1276.500000,106.6400,548.759167,3.966667,233.6800

In [52]:
south_a_df_01

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,111.5925,NaN,571.8375,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,141.1250,NaN,652.4600,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,136.1525,NaN,691.1775,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,134.1550,NaN,757.1800,NaN,NaN,100.0000
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,148.1325,NaN,837.9275,NaN,NaN,103.5900
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,159.9100,78.425000,895.1825,NaN,NaN,108.4075
6,2013,NaN,NaN,NaN,NaN,NaN,480.495000,179.6850,82.925000,967.1575,NaN,NaN,115.4075
7,2014,NaN,NaN,NaN,NaN,NaN,535.531667,189.1350,87.975000,1033.4675,2564.023333,NaN,123.9875
8,2015,NaN,101.5,79.42,NaN,209.8225,599.556667,199.0350,92.000000,1105.2025,2769.898333,NaN,131.7975
9,2016,23.79,100.2,79.42,65.34,229.7375,678.905000,207.5375,97.833333,1189.8875,2958.854167,27.450,138.2250
10,2017,24.30,95.6,79.42,65.85,244.2125,633.533333,208.1900,102.991667,1269.5475,3121.054167,27.450,143.9375
11,2018,24.58,98.1,79.42,66.36,259.4750,668.790000,213.4825,107.750000,1340.7950,3266.100000,27.125,148.9600
12,2019,25.22,102.9,79.42,66.86,275.3550,744.015000,217.5400,112.200000,1406.3025,3474.825000,28.700,152.6875
13,2020,24.18,104.5,79.42,67.35,286.7625,893.277500,191.8925,115.866667,1390.6925,3569.215000,29.175,156.3075
14,2021,25.17,104.2,79.42,67.65,298.2300,827.308333,203.4275,121.133333,1551.7100,3638.675833,34.300,166.8200
15,2022,26.17,103.2,79.42,68.33,312.9225,971.085833,236.3700,104.241667,1666.6450,3923.561667,33.500,174.0325
16,2023,27.14,NaN,NaN,68.82,337.4500,1141.587500,262.7650,110.391667,1752.2600,4204.555833,32.375,176.6175
17,2024,NaN,NaN,NaN,NaN,352.7050,1153.175833,266.9250,115.283333,1835.0950,4367.780833,32.600,178.0950

In [53]:
south_k_df_01

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,82142.900,NaN,272415.050,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,89439.875,NaN,288554.150,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,93013.925,NaN,301336.950,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,99946.475,NaN,330652.800,NaN,NaN,99.9975
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,104706.175,NaN,347234.300,NaN,NaN,105.2275
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,106403.450,91.815083,360027.825,NaN,NaN,108.2500
6,2013,NaN,NaN,NaN,NaN,NaN,333.290000,109157.000,93.009917,375204.800,NaN,NaN,107.8000
7,2014,NaN,NaN,NaN,NaN,NaN,360.684167,113147.525,94.195583,390732.250,1.656976e+06,NaN,109.4325
8,2015,NaN,101.6,17.82,NaN,62522.000,368.030000,120250.425,94.860917,414505.100,1.772220e+06,NaN,113.0825
9,2016,28.05,100.2,17.45,81.56,66323.825,371.585833,129337.475,95.782667,435194.900,1.905550e+06,3.708333,116.0900
10,2017,28.36,98.9,17.20,81.50,70761.425,381.091667,144614.250,97.645000,458924.550,2.040886e+06,3.700000,117.5950
11,2018,28.53,103.0,16.94,81.46,76173.175,400.084167,144146.800,99.086083,474548.150,2.177151e+06,3.833333,120.2225
12,2019,28.82,105.1,16.77,81.43,82165.800,404.584167,144750.550,99.465583,481124.500,2.321115e+06,3.691667,121.9325
13,2020,28.61,109.1,16.61,81.41,87396.550,416.920833,159741.700,100.000000,514616.650,2.547467e+06,3.916667,126.5600
14,2021,28.80,108.6,16.42,81.41,94567.050,456.841667,174907.700,102.498333,555478.250,2.820613e+06,3.675000,143.7325
15,2022,29.39,109.3,16.23,81.43,102466.650,438.766667,185518.475,107.715000,580945.375,3.088564e+06,2.883333,153.2175
16,2023,29.70,NaN,NaN,81.46,107037.150,421.241667,189365.075,111.590000,602171.825,3.203576e+06,2.708333,143.9875
17,2024,NaN,NaN,NaN,NaN,111764.125,415.433333,191952.050,114.180833,639214.350,3.324605e+06,2.708333,142.4575

In [54]:
uk_df_01

,Year,labor_force,livestock_prod,agr_land,urban_pop,gov_exp,reserves,investment,cpi,gdp,priv_cred,unemployment,house_price
0,2007,NaN,NaN,NaN,NaN,NaN,NaN,70.0750,NaN,386.1575,NaN,NaN,NaN
1,2008,NaN,NaN,NaN,NaN,NaN,NaN,70.3125,NaN,398.4000,NaN,NaN,NaN
2,2009,NaN,NaN,NaN,NaN,NaN,NaN,62.5150,NaN,387.2025,NaN,NaN,NaN
3,2010,NaN,NaN,NaN,NaN,NaN,NaN,64.5750,NaN,402.1400,NaN,NaN,100.0000
4,2011,NaN,NaN,NaN,NaN,NaN,NaN,65.3075,NaN,415.6475,NaN,NaN,98.5450
5,2012,NaN,NaN,NaN,NaN,NaN,NaN,67.5025,96.041667,428.4300,NaN,NaN,98.9200
6,2013,NaN,NaN,NaN,NaN,NaN,129.022500,71.1100,98.508333,445.3400,NaN,NaN,101.4550
7,2014,NaN,NaN,NaN,NaN,NaN,134.969167,77.1675,99.958333,465.6300,1594.228333,NaN,109.6025
8,2015,NaN,100.5,70.84,NaN,93.6600,149.983333,83.2450,100.008333,479.1125,1618.274167,NaN,116.1250
9,2016,33.88,100.9,71.71,82.89,95.6900,166.655833,89.1525,100.650000,497.9125,1684.606667,4.891667,124.2700
10,2017,34.07,102.5,72.20,83.14,97.1425,175.003333,95.0025,103.358333,520.6200,1734.642500,4.383333,129.9250
11,2018,34.36,104.3,71.72,83.40,99.7675,188.556667,96.8300,105.916667,538.0775,1811.995000,4.075000,134.0400
12,2019,34.63,106.0,72.42,83.65,106.6500,194.944167,101.6075,107.800000,558.4825,1873.763333,3.850000,135.3700
13,2020,34.56,106.8,71.34,83.90,118.9150,208.609167,92.0850,108.783333,525.8700,1936.857500,4.600000,139.2375
14,2021,34.24,106.5,71.16,84.15,127.1775,218.990833,101.2350,111.608333,571.3500,1985.519167,4.541667,150.5825
15,2022,34.73,105.2,69.57,84.40,131.5625,212.458333,112.7750,120.450000,631.6075,2058.680000,3.783333,164.5475
16,2023,35.19,NaN,NaN,84.64,140.6150,208.479167,119.5125,128.633333,677.7950,2088.522500,4.066667,165.0025
17,2024,NaN,NaN,NaN,NaN,149.6275,217.076667,124.0375,132.841667,712.7475,2098.692500,4.066667,166.3750